      SUBROUTINE alloc_clinam  
      
      USE CLINAM
      
      IMPLICIT NONE
      INTEGER :: istat = 0 
      
        IF(.NOT.ALLOCATED(nnp))ALLOCATE ( nnp(27), STAT=istat)
        nnp = 0 
        ALLOCATE ( icnt(20), STAT=istat)
        icnt = 0 
        ALLOCATE ( name(8), STAT=istat)
        name = " "
        ALLOCATE ( lmix(psaw), STAT=istat)
        lmix = 0  
        ALLOCATE ( ibaloon(ppsi), STAT=istat)
        ibaloon = 0 
        ALLOCATE ( iseries(pngroup), STAT=istat)
        iseries = 0 
        ALLOCATE ( lgroup(pngroup), STAT=istat)
        lgroup = 0 
        ALLOCATE ( jnreg(pngroup), STAT=istat)
        jnreg = 0 
        ALLOCATE ( nogroupt(pngroup), STAT=istat)
        nogroupt = 0 
        ALLOCATE ( icmaxs(pngroup), STAT=istat)
        icmaxs = 0 
        ALLOCATE ( nogroup(pngroup), STAT=istat)
        nogroup = 0 
        ALLOCATE ( nogroups(pngroup), STAT=istat)
        nogroups = 0 
        ALLOCATE ( indxd1(pnfeed), STAT=istat)
        indxd1 = 0 
        ALLOCATE ( idelay(pnfeed), STAT=istat)
        idelay = 0 
        ALLOCATE ( nfeedo(pnfeed), STAT=istat)
        nfeedo = 0 
        ALLOCATE ( nfeed2(pnfeed), STAT=istat)
        nfeed2 = 0 
        ALLOCATE ( nrfb(pnfeed), STAT=istat)
        nrfb = 0 
        ALLOCATE ( ipext(pnfeed), STAT=istat)
        ipext = 0 
        ALLOCATE ( iflagfb(pnfeed), STAT=istat)
        iflagfb = 0 
        ALLOCATE ( igroupc(pncoil), STAT=istat)
        igroupc = 0 
        ALLOCATE ( ilcoil(pncoil), STAT=istat)
        ilcoil = 0 
        ALLOCATE ( izsep(pnsep), STAT=istat)
        izsep = 0 
        ALLOCATE ( jzsep(pnsep), STAT=istat)
        jzsep = 0 
        ALLOCATE ( izsepo(pnsep), STAT=istat)
        izsepo = 0 
        ALLOCATE ( jzsepo(pnsep), STAT=istat)
        jzsepo = 0 
        ALLOCATE ( ngrvw1(pnwire), STAT=istat)
        ngrvw1 = 0 
        ALLOCATE ( iwire(pnwire), STAT=istat)
        iwire = 0 
        ALLOCATE ( jwire(pnwire), STAT=istat)
        jwire = 0 
        ALLOCATE ( ngrvw2(pnwire), STAT=istat)
        ngrvw2 = 0 
        ALLOCATE ( ifeed(pnwire), STAT=istat)
        ifeed = 0 
        ALLOCATE ( igroupw(pnwire), STAT=istat)
        igroupw = 0 
        ALLOCATE ( ngrvw3(pnwire), STAT=istat)
        ngrvw3 = 0 
        ALLOCATE ( ngrvw4(pnwire), STAT=istat)
        ngrvw4 = 0 
        ALLOCATE ( ngrvc1(pncoil), STAT=istat) !cj        ALLOCATE ( ngrvc1(pnwire), STAT=istat)
        ngrvc1 = 0 
        ALLOCATE ( ngrvc2(pncoil), STAT=istat) !cj        ALLOCATE ( ngrvc2(pnwire), STAT=istat)
        ngrvc2 = 0 
        ALLOCATE ( ngrvc3(pncoil), STAT=istat) !cj        ALLOCATE ( ngrvc3(pnwire), STAT=istat)
        ngrvc3 = 0 
        ALLOCATE ( ngrvc4(pncoil), STAT=istat) !cj        ALLOCATE ( ngrvc4(pnwire), STAT=istat)
        ngrvc4 = 0 
        ALLOCATE ( ilwire(pnwire), STAT=istat)
        ilwire = 0 
        ALLOCATE ( iobs(pobs), STAT=istat)
        iobs = 0 
        ALLOCATE ( jobs(pobs), STAT=istat)
        jobs = 0 
        ALLOCATE ( npltobs(pobs), STAT=istat)
        npltobs = 0 
        ALLOCATE ( ilima(pnlim), STAT=istat)
        ilima = 0 
        ALLOCATE ( jlima(pnlim), STAT=istat)
        jlima = 0 
        ALLOCATE ( nseg(pnplat), STAT=istat)
        nseg = 0 
        ALLOCATE ( iptch(pkw), STAT=istat)
        iptch = 0 
        ALLOCATE ( nsegs(pkw), STAT=istat)
        nsegs = 0 
        ALLOCATE ( impnum(18), STAT=istat)
        impnum = 0 
        ALLOCATE ( ichargst(18), STAT=istat)
        ichargst = 0 
        ALLOCATE ( iexvc(penx,penz), STAT=istat)
        iexvc = 0 
        ALLOCATE ( icoil(penx,penz), STAT=istat)
        icoil = 0 
        ALLOCATE ( iexv(penx,penz), STAT=istat)
        iexv = 0 
        ALLOCATE ( iexs(penx,penz), STAT=istat)
        iexs = 0 
        ALLOCATE ( nfeedv(ptpts,pnfeed), STAT=istat)
        nfeedv = 0 
        ALLOCATE ( icoils(pnwire,pngrps), STAT=istat)
        icoils = 0 
        ALLOCATE ( ifrst(50), STAT=istat)
        ifrst = 0 
        ALLOCATE ( noplot(100), STAT=istat)
        noplot = 0 
        ALLOCATE ( iminy(250), STAT=istat)
        iminy = 0 
        ALLOCATE ( imaxy(250), STAT=istat)
        imaxy = 0 
        ALLOCATE ( jminy(250), STAT=istat)
        jminy = 0 
        ALLOCATE ( jmaxy(250), STAT=istat)
        jmaxy = 0 
        ALLOCATE ( jminny(pnx), STAT=istat)
        jminny = 0 
        ALLOCATE ( jmaxxy(pnx), STAT=istat)
        jmaxxy = 0 
        ALLOCATE ( acoef(4999+pncoil), STAT=istat)
        acoef = 0 
        ALLOCATE ( redef(4999+pncoil), STAT=istat)
        redef = 0 
        ALLOCATE ( global(pglob), STAT=istat)
        global = 0 
        ALLOCATE ( sawtime(psaw), STAT=istat)
        sawtime = 0 
        ALLOCATE ( cisum(5), STAT=istat)
        cisum = 0 
        ALLOCATE ( cmomo(2,2), STAT=istat)
        cmomo = 0 
        ALLOCATE ( cmom(2,2), STAT=istat)
        cmom = 0 
        ALLOCATE ( xsep(pnsep), STAT=istat)
        xsep = 0 
        ALLOCATE ( zsep(pnsep), STAT=istat)
        zsep = 0 
        ALLOCATE ( psep(pnsep), STAT=istat)
        psep = 0 
        ALLOCATE ( engrupi(pngroup), STAT=istat)
        engrupi = 0 
        ALLOCATE ( gvsuma(pngroup), STAT=istat)
        gvsuma = 0 
        ALLOCATE ( delv(pngroup), STAT=istat)
        delv = 0 
        ALLOCATE ( engroup(pngroup), STAT=istat)
        engroup = 0 
        ALLOCATE ( globmin(pgls), STAT=istat)
        globmin = 0 
        ALLOCATE ( globmax(pgls), STAT=istat)
        globmax = 0 
        ALLOCATE ( xplot(6,2*pnparts), STAT=istat)
        xplot = 0 
        ALLOCATE ( zplot(6,2*pnparts), STAT=istat)
        zplot = 0 
        ALLOCATE ( pltsav(2*pnsave*pglobp), STAT=istat)
        pltsav = 0 
        ALLOCATE ( apld0sv(2*pnsave), STAT=istat)
        apld0sv = 0 
        ALLOCATE ( fluxu(pobs,2*pnsave), STAT=istat)
        fluxu = 0 
        ALLOCATE ( fluxl(pobs,2*pnsave), STAT=istat)
        fluxl = 0 
        ALLOCATE ( xary(penx), STAT=istat)
        xary = 0 
        ALLOCATE ( xsqoj(penx), STAT=istat)
        xsqoj = 0 
        ALLOCATE ( ajey(penx), STAT=istat)
        ajey = 0 
        ALLOCATE ( xarh(penx), STAT=istat)
        xarh = 0 
        ALLOCATE ( zary(penz), STAT=istat)
        zary = 0 
        ALLOCATE ( vzy(penz), STAT=istat)
        vzy = 0 
        ALLOCATE ( w11(penx+2*penz), STAT=istat)
        w11 = 0 
        ALLOCATE ( w12(penx+2*penz), STAT=istat)
        w12 = 0 
        ALLOCATE ( psi(penx,penz), STAT=istat)
        psi = 0 
        ALLOCATE ( ajphi(penx,penz), STAT=istat)
        ajphi = 0 
        ALLOCATE ( vd(penx,penz), STAT=istat)
        vd = 0 
        ALLOCATE ( gs(penx,penz), STAT=istat)
        gs = 0 
        ALLOCATE ( g(penx,penz), STAT=istat)
        g = 0 
        ALLOCATE ( q(penx,penz), STAT=istat)
        q = 0 
        ALLOCATE ( psio(penx,penz), STAT=istat)
        psio = 0 
        ALLOCATE ( psizer(penx,penz), STAT=istat)
        psizer = 0 
        ALLOCATE ( rjcd(penx,penz), STAT=istat)
        rjcd = 0 
        ALLOCATE ( rjcd2(penx,penz), STAT=istat)
        rjcd2 = 0 
        ALLOCATE ( cgroup(pngroup), STAT=istat)
        cgroup = 0 
        ALLOCATE ( sgroup(pngroup), STAT=istat)
        sgroup = 0 
        ALLOCATE ( wo(pnx,pnz), STAT=istat)
        wo = 0 
        ALLOCATE ( go(pnx,pnz), STAT=istat)
        go = 0 
        ALLOCATE ( uo(pnx,pnz), STAT=istat)
        uo = 0 
        ALLOCATE ( abig(pnx,pnz), STAT=istat)
        abig = 0 
        ALLOCATE ( rsurf(pnx,pnz), STAT=istat)
        rsurf = 0 
        ALLOCATE ( b(pnx,pnz), STAT=istat)
        b = 0 
        ALLOCATE ( bo(pnx,pnz), STAT=istat)
        bo = 0 
        ALLOCATE ( uary(pnx,pnz), STAT=istat)
        uary = 0 
        ALLOCATE ( omeg(pnx,pnz), STAT=istat)
        omeg = 0 
        ALLOCATE ( etay(pnx,pnz), STAT=istat)
        etay = 0 
        ALLOCATE ( bsqsv(pnx,pnz), STAT=istat)
        bsqsv = 0 
        ALLOCATE ( rdens(pnx,pnz), STAT=istat)
        rdens = 0 
        ALLOCATE ( rjdb(pnx,pnz), STAT=istat)
        rjdb = 0 
        ALLOCATE ( w(pnx,pnz), STAT=istat)
        w = 0 
        ALLOCATE ( u(pnx,pnz), STAT=istat)
        u = 0 
        ALLOCATE ( qo(pnx,pnz), STAT=istat)
        qo = 0 
        ALLOCATE ( r(pnx,pnz), STAT=istat)
        r = 0 
        ALLOCATE ( ro(pnx,pnz), STAT=istat)
        ro = 0 
        ALLOCATE ( qsurf(pnx,pnz), STAT=istat)
        qsurf = 0 
        ALLOCATE ( pr(pnx,pnz), STAT=istat)
        pr = 0 
        ALLOCATE ( pro(pnx,pnz), STAT=istat)
        pro = 0 
        ALLOCATE ( roj(pnx,pnz), STAT=istat)
        roj = 0 
        ALLOCATE ( go2(pnx,pnz), STAT=istat)
        go2 = 0 
        ALLOCATE ( pso2(pnx,pnz), STAT=istat)
        pso2 = 0 
        ALLOCATE ( uo2(pnx,pnz), STAT=istat)
        uo2 = 0 
        ALLOCATE ( bmagy(pnx,pnz), STAT=istat)
        bmagy = 0 
        ALLOCATE ( ptsave(pnx,pnz), STAT=istat)
        ptsave = 0 
        ALLOCATE ( gtsave(pnx,pnz), STAT=istat)
        gtsave = 0 
        ALLOCATE ( psibl(penz), STAT=istat)
        psibl = 0 
        ALLOCATE ( psibr(penz), STAT=istat)
        psibr = 0 
        ALLOCATE ( psitl(penz), STAT=istat)
        psitl = 0 
        ALLOCATE ( psitr(penz), STAT=istat)
        psitr = 0 
        ALLOCATE ( psisl(penz), STAT=istat)
        psisl = 0 
        ALLOCATE ( psisr(penz), STAT=istat)
        psisr = 0 
        ALLOCATE ( psiblo(penz), STAT=istat)
        psiblo = 0 
        ALLOCATE ( psibro(penz), STAT=istat)
        psibro = 0 
        ALLOCATE ( psiobl(penz), STAT=istat)
        psiobl = 0 
        ALLOCATE ( psiobr(penz), STAT=istat)
        psiobr = 0 
        ALLOCATE ( psidbl(penz), STAT=istat)
        psidbl = 0 
        ALLOCATE ( psidbr(penz), STAT=istat)
        psidbr = 0 
        ALLOCATE ( omderr(penz), STAT=istat)
        omderr = 0 
        ALLOCATE ( omderl(penz), STAT=istat)
        omderl = 0 
        ALLOCATE ( avbndl(penz), STAT=istat)
        avbndl = 0 
        ALLOCATE ( avbndr(penz), STAT=istat)
        avbndr = 0 
        ALLOCATE ( psibb(penx), STAT=istat)
        psibb = 0 
        ALLOCATE ( psibt(penx), STAT=istat)
        psibt = 0 
        ALLOCATE ( psitb(penx), STAT=istat)
        psitb = 0 
        ALLOCATE ( psitt(penx), STAT=istat)
        psitt = 0 
        ALLOCATE ( psisb(penx), STAT=istat)
        psisb = 0 
        ALLOCATE ( psist(penx), STAT=istat)
        psist = 0 
        ALLOCATE ( psibbo(penx), STAT=istat)
        psibbo = 0 
        ALLOCATE ( psibto(penx), STAT=istat)
        psibto = 0 
        ALLOCATE ( psiobb(penx), STAT=istat)
        psiobb = 0 
        ALLOCATE ( psiobt(penx), STAT=istat)
        psiobt = 0 
        ALLOCATE ( psidbb(penx), STAT=istat)
        psidbb = 0 
        ALLOCATE ( psidbt(penx), STAT=istat)
        psidbt = 0 
        ALLOCATE ( omderb(penx), STAT=istat)
        omderb = 0 
        ALLOCATE ( omdert(penx), STAT=istat)
        omdert = 0 
        ALLOCATE ( avbndb(penx), STAT=istat)
        avbndb = 0 
        ALLOCATE ( avbndt(penx), STAT=istat)
        avbndt = 0 
        ALLOCATE ( vn(pboun), STAT=istat)
        vn = 0 
        ALLOCATE ( psiold(pboun), STAT=istat)
        psiold = 0 
        ALLOCATE ( gcurfb(pngroup), STAT=istat)
        gcurfb = 0 
        ALLOCATE ( gcurfbo(pngroup), STAT=istat)
        gcurfbo = 0 
        ALLOCATE ( gvgpmax(pngroup), STAT=istat)
        gvgpmax = 0 
        ALLOCATE ( gvgpmin(pngroup), STAT=istat)
        gvgpmin = 0 
        ALLOCATE ( gpgpmax(pngroup), STAT=istat)
        gpgpmax = 0 
        ALLOCATE ( gpgpmin(pngroup), STAT=istat)
        gpgpmin = 0 
        ALLOCATE ( gigpmax(pngroup), STAT=istat)
        gigpmax = 0 
        ALLOCATE ( gigpmin(pngroup), STAT=istat)
        gigpmin = 0 
        ALLOCATE ( gvolt0(pngroup), STAT=istat)
        gvolt0 = 0 
        ALLOCATE ( fsave1(pnfeed,pdelay), STAT=istat)
        fsave1 = 0 
        ALLOCATE ( sumfeed(pnfeed), STAT=istat)
        sumfeed = 0 
        ALLOCATE ( savfeed(pnfeed), STAT=istat)
        savfeed = 0 
        ALLOCATE ( xcon0(ptpts,10), STAT=istat)
        xcon0 = 0 
        ALLOCATE ( zcon0(ptpts,10), STAT=istat)
        zcon0 = 0 
        ALLOCATE ( fadj(pngroup,pncoil), STAT=istat)
        fadj = 0 
        ALLOCATE ( amats(20,20,pdelay), STAT=istat)
        amats = 0 
        ALLOCATE ( bvecs(20,pdelay), STAT=istat)
        bvecs = 0 
        ALLOCATE ( shpsum(20), STAT=istat)
        shpsum = 0 
        ALLOCATE ( shpdif(20), STAT=istat)
        shpdif = 0 
        ALLOCATE ( shpdifo(20), STAT=istat)
        shpdifo = 0 
        ALLOCATE ( xveh(201), STAT=istat)
        xveh = 0 
        ALLOCATE ( wmega(200), STAT=istat)
        wmega = 0 
        ALLOCATE ( phin(200), STAT=istat)
        phin = 0 
        ALLOCATE ( sigmasvd(pngroup), STAT=istat)
        sigmasvd = 0 
        ALLOCATE ( fluxu0(pobs), STAT=istat)
        fluxu0 = 0 
        ALLOCATE ( fluxl0(pobs), STAT=istat)
        fluxl0 = 0 
        ALLOCATE ( xobs(pobs), STAT=istat)
        xobs = 0 
        ALLOCATE ( zobs(pobs), STAT=istat)
        zobs = 0 
        ALLOCATE ( tfbons(pnfeed), STAT=istat)
        tfbons = 0 
        ALLOCATE ( tfbon(pnfeed), STAT=istat)
        tfbon = 0 
        ALLOCATE ( tfbofs(pnfeed), STAT=istat)
        tfbofs = 0 
        ALLOCATE ( tfbof(pnfeed), STAT=istat)
        tfbof = 0 
        ALLOCATE ( fbfac(pnfeed), STAT=istat)
        fbfac = 0 
        ALLOCATE ( fbcon(pnfeed), STAT=istat)
        fbcon = 0 
        ALLOCATE ( fbfac1(pnfeed), STAT=istat)
        fbfac1 = 0 
        ALLOCATE ( tzerfba(pnfeed), STAT=istat)
        tzerfba = 0 
        ALLOCATE ( fbfacd(pnfeed), STAT=istat)
        fbfacd = 0 
        ALLOCATE ( tperfba(pnfeed), STAT=istat)
        tperfba = 0 
        ALLOCATE ( fbfaci(pnfeed), STAT=istat)
        fbfaci = 0 
        ALLOCATE ( gcur(ptpts,pngroup), STAT=istat)
        gcur = 0 
        ALLOCATE ( pcur(ptpts), STAT=istat)
        pcur = 0 
        ALLOCATE ( ppres(ptpts), STAT=istat)
        ppres = 0 
        ALLOCATE ( tpro(ptpts), STAT=istat)
        tpro = 0 
        ALLOCATE ( tpros(ptpts), STAT=istat)
        tpros = 0 
        ALLOCATE ( gzerov(ptpts), STAT=istat)
        gzerov = 0 
        ALLOCATE ( beamp(ptpts), STAT=istat)
        beamp = 0 
        ALLOCATE ( rnorm(ptpts), STAT=istat)
        rnorm = 0 
        ALLOCATE ( fact(ptpts), STAT=istat)
        fact = 0 
        ALLOCATE ( fbchia(ptpts), STAT=istat)
        fbchia = 0 
        ALLOCATE ( fbchiia(ptpts), STAT=istat)
        fbchiia = 0 
        ALLOCATE ( facd(ptpts), STAT=istat)
        facd = 0 
        ALLOCATE ( vloopv(ptpts), STAT=istat)
        vloopv = 0 
        ALLOCATE ( xmagz(ptpts), STAT=istat)
        xmagz = 0 
        ALLOCATE ( zmagz(ptpts), STAT=istat)
        zmagz = 0 
        ALLOCATE ( tevv0(ptpts), STAT=istat)
        tevv0 = 0 
        ALLOCATE ( ffac0(ptpts), STAT=istat)
        ffac0 = 0 
        ALLOCATE ( rzerv(ptpts), STAT=istat)
        rzerv = 0 
        ALLOCATE ( azerv(ptpts), STAT=istat)
        azerv = 0 
        ALLOCATE ( zeffv(ptpts), STAT=istat)
        zeffv = 0 
        ALLOCATE ( resgs(pngroup), STAT=istat)
        resgs = 0 
        ALLOCATE ( tpest(100), STAT=istat)
        tpest = 0 
        ALLOCATE ( ezerv(ptpts), STAT=istat)
        ezerv = 0 
        ALLOCATE ( dzerv(ptpts), STAT=istat)
        dzerv = 0 
        ALLOCATE ( plhamp(ptpts), STAT=istat)
        plhamp = 0 
        ALLOCATE ( betarv(ptpts), STAT=istat)
        betarv = 0 
        ALLOCATE ( alpharv(ptpts), STAT=istat)
        alpharv = 0 
        ALLOCATE ( frcparv(ptpts), STAT=istat)
        frcparv = 0 
        ALLOCATE ( alhd(ptpts), STAT=istat)
        alhd = 0 
        ALLOCATE ( dlhd(ptpts), STAT=istat)
        dlhd = 0 
        ALLOCATE ( a1lhd(ptpts), STAT=istat)
        a1lhd = 0 
        ALLOCATE ( a2lhd(ptpts), STAT=istat)
        a2lhd = 0 
        ALLOCATE ( aclhd(ptpts), STAT=istat)
        aclhd = 0 
        ALLOCATE ( dclhd(ptpts), STAT=istat)
        dclhd = 0 
        ALLOCATE ( a1clhd(ptpts), STAT=istat)
        a1clhd = 0 
        ALLOCATE ( a2clhd(ptpts), STAT=istat)
        a2clhd = 0 
        ALLOCATE ( afwd(ptpts), STAT=istat)
        afwd = 0 
        ALLOCATE ( dfwd(ptpts), STAT=istat)
        dfwd = 0 
        ALLOCATE ( a1fwd(ptpts), STAT=istat)
        a1fwd = 0 
        ALLOCATE ( a2fwd(ptpts), STAT=istat)
        a2fwd = 0 
        ALLOCATE ( acfwd(ptpts), STAT=istat)
        acfwd = 0 
        ALLOCATE ( dcfwd(ptpts), STAT=istat)
        dcfwd = 0 
        ALLOCATE ( a1cfwd(ptpts), STAT=istat)
        a1cfwd = 0 
        ALLOCATE ( a2cfwd(ptpts), STAT=istat)
        a2cfwd = 0 
        ALLOCATE ( thalov(ptpts), STAT=istat)
        thalov = 0 
        ALLOCATE ( whalov(ptpts), STAT=istat)
        whalov = 0 
        ALLOCATE ( picrh(ptpts), STAT=istat)
        picrh = 0
        ALLOCATE ( fwcd(ptpts), STAT=istat)
        fwcd = 0
        ALLOCATE ( heactv(ptpts), STAT=istat)
        heactv = 0 
!
        ALLOCATE ( pecrh(ptpts), STAT=istat)
        pecrh = 0
        ALLOCATE ( eccd(ptpts), STAT=istat)
        eccd = 0
        ALLOCATE ( aecd(ptpts), STAT=istat)
        aecd = 0
        ALLOCATE ( decd(ptpts), STAT=istat)
        decd = 0
        ALLOCATE ( a1ecd(ptpts), STAT=istat)
        a1ecd = 0
        ALLOCATE ( a2ecd(ptpts), STAT=istat)
        a2ecd = 0
!
        ALLOCATE (tpedv(ptpts), STAT=istat)
        tpedv = 0
        ALLOCATE (qaddv(ptpts), STAT=istat)
        qaddv = 0
        ALLOCATE (fhmodeiv(ptpts), STAT=istat)
        fhmodeiv = 0
        ALLOCATE (pwidthcv(ptpts), STAT=istat)
        pwidthcv = 0
        ALLOCATE (chipedv(ptpts), STAT=istat)
        chipedv = 0
        ALLOCATE (fraciv(8,ptpts), STAT=istat)
        fraciv = 0
        ALLOCATE (nflagv(ptpts), STAT=istat)
        nflagv = 0
        ALLOCATE (expn1v(ptpts), STAT=istat)
        expn1v = 0
        ALLOCATE (expn2v(ptpts), STAT=istat)
        expn2v = 0
        ALLOCATE (firitbv(ptpts), STAT=istat)
        firitbv = 0
        ALLOCATE (secitbv(ptpts), STAT=istat)
        secitbv = 0
        ALLOCATE (fracn0v(ptpts), STAT=istat)
        fracn0v = 0
        ALLOCATE (newdenv(ptpts), STAT=istat)
        newdenv = 0
!
        ALLOCATE ( atnvw1(ptpts,pnwire), STAT=istat)
        atnvw1 = 0 
        ALLOCATE ( atnvw2(ptpts,pnwire), STAT=istat)
        atnvw2 = 0 
        ALLOCATE ( atnvw3(ptpts,pnwire), STAT=istat)
        atnvw3 = 0 
        ALLOCATE ( atnvw4(ptpts,pnwire), STAT=istat)
        atnvw4 = 0 
        ALLOCATE ( atnvc1(ptpts,pncoil), STAT=istat) !cj        ALLOCATE ( atnvc1(ptpts,pnwire), STAT=istat)
        atnvc1 = 0 
        ALLOCATE ( atnvc2(ptpts,pncoil), STAT=istat) !cj        ALLOCATE ( atnvc2(ptpts,pnwire), STAT=istat)
        atnvc2 = 0 
        ALLOCATE ( atnvc3(ptpts,pncoil), STAT=istat) !cj        ALLOCATE ( atnvc2(ptpts,pnwire), STAT=istat)
        atnvc3 = 0 
        ALLOCATE ( atnvc4(ptpts,pncoil), STAT=istat) !cj        ALLOCATE ( atnvc4(ptpts,pnwire), STAT=istat)
        atnvc4 = 0 
        ALLOCATE ( xcoil(pncoil), STAT=istat)
        xcoil = 0 
        ALLOCATE ( zcoil(pncoil), STAT=istat)
        zcoil = 0 
        ALLOCATE ( ccoil(pncoil), STAT=istat)
        ccoil = 0 
        ALLOCATE ( dcoil(pncoil), STAT=istat)
        dcoil = 0 
        ALLOCATE ( ccoils(pncoil), STAT=istat)
        ccoils = 0 
        ALLOCATE ( aturnsc(pncoil), STAT=istat)
        aturnsc = 0 
        ALLOCATE ( rscoil(pncoil), STAT=istat)
        rscoil = 0 
        ALLOCATE ( rscoils(pncoil), STAT=istat)
        rscoils = 0 
        ALLOCATE ( aindc(pncoil), STAT=istat)
        aindc = 0 
        ALLOCATE ( ccoil0(pncoil), STAT=istat)
        ccoil0 = 0 
        ALLOCATE ( worksp(pncoil), STAT=istat)
        worksp = 0 
        ALLOCATE ( xwire(pnwire), STAT=istat)
        xwire = 0 
        ALLOCATE ( zwire(pnwire), STAT=istat)
        zwire = 0 
        ALLOCATE ( cwics(pnwire), STAT=istat)
        cwics = 0 
        ALLOCATE ( rswire(pnwire), STAT=istat)
        rswire = 0 
        ALLOCATE ( rswires(pnwire), STAT=istat)
        rswires = 0 
        ALLOCATE ( cwires(pnwire), STAT=istat)
        cwires = 0 
        ALLOCATE ( cwire0(pnwire), STAT=istat)
        cwire0 = 0 
        ALLOCATE ( cwiradi(pnwire), STAT=istat)
        cwiradi = 0 
        ALLOCATE ( ajwire(pnwire), STAT=istat)
        ajwire = 0 
        ALLOCATE ( aturnsw(pnwire), STAT=istat)
        aturnsw = 0 
        ALLOCATE ( aindw(pnwire), STAT=istat)
        aindw = 0 
        ALLOCATE ( resave(pnwire), STAT=istat)
        resave = 0 
        ALLOCATE ( xlima(pnlim), STAT=istat)
        xlima = 0 
        ALLOCATE ( zlima(pnlim), STAT=istat)
        zlima = 0 
        ALLOCATE ( as0(ppsi), STAT=istat)
        as0 = 0 
        ALLOCATE ( as1(ppsi), STAT=istat)
        as1 = 0 
        ALLOCATE ( as2(ppsi), STAT=istat)
        as2 = 0 
        ALLOCATE ( as3(ppsi), STAT=istat)
        as3 = 0 
        ALLOCATE ( as4(ppsi), STAT=istat)
        as4 = 0 
        ALLOCATE ( cs0(ppsi), STAT=istat)
        cs0 = 0 
        ALLOCATE ( cs1(ppsi), STAT=istat)
        cs1 = 0 
        ALLOCATE ( cs2(ppsi), STAT=istat)
        cs2 = 0 
        ALLOCATE ( cs3(ppsi), STAT=istat)
        cs3 = 0 
        ALLOCATE ( cs4(ppsi), STAT=istat)
        cs4 = 0 
        ALLOCATE ( dsi0(ppsi), STAT=istat)
        dsi0 = 0 
        ALLOCATE ( dsi1(ppsi), STAT=istat)
        dsi1 = 0 
        ALLOCATE ( dsi2(ppsi), STAT=istat)
        dsi2 = 0 
        ALLOCATE ( dsi3(ppsi), STAT=istat)
        dsi3 = 0 
        ALLOCATE ( dsi4(ppsi), STAT=istat)
        dsi4 = 0 
        ALLOCATE ( dse0(ppsi), STAT=istat)
        dse0 = 0 
        ALLOCATE ( dse1(ppsi), STAT=istat)
        dse1 = 0 
        ALLOCATE ( dse2(ppsi), STAT=istat)
        dse2 = 0 
        ALLOCATE ( dse3(ppsi), STAT=istat)
        dse3 = 0 
        ALLOCATE ( dse4(ppsi), STAT=istat)
        dse4 = 0 
        ALLOCATE ( gam(ppsi), STAT=istat)
        gam = 0 
        ALLOCATE ( as(ppsi), STAT=istat)
        as = 0 
        ALLOCATE ( cs(ppsi), STAT=istat)
        cs = 0 
        ALLOCATE ( dsi(ppsi), STAT=istat)
        dsi = 0 
        ALLOCATE ( dse(ppsi), STAT=istat)
        dse = 0 
        ALLOCATE ( vary(ppsi), STAT=istat)
        vary = 0 
        ALLOCATE ( anue(ppsi), STAT=istat)
        anue = 0 
        ALLOCATE ( vp(ppsi), STAT=istat)
        vp = 0 
        ALLOCATE ( vp2(ppsi), STAT=istat)
        vp2 = 0 
        ALLOCATE ( vpg(ppsi), STAT=istat)
        vpg = 0 
        ALLOCATE ( xmja(ppsi), STAT=istat)
        xmja = 0 
        ALLOCATE ( adpo(ppsi), STAT=istat)
        adpo = 0 
        ALLOCATE ( adeo(ppsi), STAT=istat)
        adeo = 0 
        ALLOCATE ( adno(ppsi), STAT=istat)
        adno = 0 
        ALLOCATE ( adio(ppsi), STAT=istat)
        adio = 0 
        ALLOCATE ( adi(ppsi), STAT=istat)
        adi = 0 
        ALLOCATE ( adp(ppsi), STAT=istat)
        adp = 0 
        ALLOCATE ( ade(ppsi), STAT=istat)
        ade = 0 
        ALLOCATE ( adn(ppsi), STAT=istat)
        adn = 0 
        ALLOCATE ( adpi(ppsi), STAT=istat)
        adpi = 0 
        ALLOCATE (adoo(ppsi), STAT=istat)
        adoo = 0
        ALLOCATE (ado(ppsi), STAT=istat)
        ado = 0
        ALLOCATE (d2pi(ppsi), STAT=istat)
        d2pi = 0
        ALLOCATE (d2pe(ppsi), STAT=istat)
        d2pe = 0
        ALLOCATE (d2s(ppsi), STAT=istat)
        d2s = 0
        ALLOCATE ( qamin(ppsi), STAT=istat)
        qamin = 0 
        ALLOCATE ( bsqar(ppsi), STAT=istat)
        bsqar = 0 
        ALLOCATE ( bsqiar(ppsi), STAT=istat)
        bsqiar = 0 
        ALLOCATE ( bpolar(ppsi), STAT=istat)
        bpolar = 0 
        ALLOCATE ( flux0(ppsi), STAT=istat)
        flux0 = 0 
        ALLOCATE ( flux10(ppsi), STAT=istat)
        flux10 = 0 
        ALLOCATE ( flux20(ppsi), STAT=istat)
        flux20 = 0 
        ALLOCATE ( flux30(ppsi), STAT=istat)
        flux30 = 0 
        ALLOCATE ( chiitima(ppsi), STAT=istat)
        chiitima = 0 
        ALLOCATE ( chietema(ppsi), STAT=istat)
        chietema = 0 
        ALLOCATE ( diffnema(ppsi), STAT=istat)
        diffnema = 0 
        ALLOCATE ( chiitimao(ppsi), STAT=istat)
        chiitimao = 0 
        ALLOCATE ( chietemao(ppsi), STAT=istat)
        chietemao = 0 
        ALLOCATE ( diffnemao(ppsi), STAT=istat)
        diffnemao = 0 
        ALLOCATE ( dchii_dtip(ppsi), STAT=istat)
        dchii_dtip = 0 
        ALLOCATE ( dchii_dtep(ppsi), STAT=istat)
        dchii_dtep = 0 
        ALLOCATE ( dchie_dtip(ppsi), STAT=istat)
        dchie_dtip = 0 
        ALLOCATE ( dchie_dtep(ppsi), STAT=istat)
        dchie_dtep = 0 
        ALLOCATE ( dti_dpsi(ppsi), STAT=istat)
        dti_dpsi = 0 
        ALLOCATE ( dte_dpsi(ppsi), STAT=istat)
        dte_dpsi = 0 
        ALLOCATE ( velthi11(ppsi), STAT=istat)
        velthi11 = 0 
        ALLOCATE ( velthi21(ppsi), STAT=istat)
        velthi21 = 0 
        ALLOCATE ( velthi31(ppsi), STAT=istat)
        velthi31 = 0 
        ALLOCATE ( ratioi(ppsi), STAT=istat)
        ratioi = 0 
        ALLOCATE ( ratioe(ppsi), STAT=istat)
        ratioe = 0 
        ALLOCATE ( equila(ppsi), STAT=istat)
        equila = 0 
        ALLOCATE ( etpara(ppsi), STAT=istat)
        etpara = 0 
        ALLOCATE ( deltaa(ppsi), STAT=istat)
        deltaa = 0 
        ALLOCATE ( gxmja(ppsi), STAT=istat)
        gxmja = 0 
        ALLOCATE ( gxmja2(ppsi), STAT=istat)
        gxmja2 = 0 
        ALLOCATE ( xmja2(ppsi), STAT=istat)
        xmja2 = 0 
        ALLOCATE ( savei(ppsi), STAT=istat)
        savei = 0 
        ALLOCATE ( savee(ppsi), STAT=istat)
        savee = 0 
        ALLOCATE ( srave(ppsi), STAT=istat)
        srave = 0 
        ALLOCATE ( polflx(ppsi), STAT=istat)
        polflx = 0 
        ALLOCATE ( torflx(ppsi), STAT=istat)
        torflx = 0 
        ALLOCATE ( qprof(ppsi), STAT=istat)
        qprof = 0 
        ALLOCATE ( temflx(ppsi), STAT=istat)
        temflx = 0 
        ALLOCATE ( volflx(ppsi), STAT=istat)
        volflx = 0 
        ALLOCATE ( tprof(ppsi), STAT=istat)
        tprof = 0 
        ALLOCATE ( gprof(ppsi), STAT=istat)
        gprof = 0 
        ALLOCATE ( gemflx(ppsi), STAT=istat)
        gemflx = 0 
        ALLOCATE ( xsv2(ppsi), STAT=istat)
        xsv2 = 0 
        ALLOCATE ( xsv(ppsi), STAT=istat)
        xsv = 0 
        ALLOCATE ( ftrap(ppsi), STAT=istat)
        ftrap = 0 
        ALLOCATE ( savia(ppsi), STAT=istat)
        savia = 0 
        ALLOCATE ( avhyp(ppsi), STAT=istat)
        avhyp = 0 
        ALLOCATE ( sraveb(ppsi), STAT=istat)
        sraveb = 0 
        ALLOCATE ( vlooph(ppsi), STAT=istat)
        vlooph = 0 
        ALLOCATE ( alphanu(ppsi), STAT=istat)
        alphanu = 0 
        ALLOCATE ( sraveedg(ppsi), STAT=istat)
        sraveedg = 0 
        ALLOCATE ( dperpa(ppsi), STAT=istat)
        dperpa = 0 
        ALLOCATE ( aplosts(ppsi), STAT=istat)
        aplosts = 0 
        ALLOCATE ( aplostsr(ppsi), STAT=istat)
        aplostsr = 0 
        ALLOCATE ( savea(ppsi), STAT=istat)
        savea = 0 
        ALLOCATE ( savebre(ppsi), STAT=istat)
        savebre = 0 
        ALLOCATE ( savecyc(ppsi), STAT=istat)
        savecyc = 0 
        ALLOCATE ( saveimp(ppsi), STAT=istat)
        saveimp = 0 
        ALLOCATE ( savefw(ppsi), STAT=istat)
        savefw = 0 
        ALLOCATE ( savifw(ppsi), STAT=istat)
        savifw = 0 
        ALLOCATE ( anhe(ppsi), STAT=istat)
        anhe = 0 
        ALLOCATE ( savebm(ppsi), STAT=istat)
        savebm = 0 
        ALLOCATE ( savibm(ppsi), STAT=istat)
        savibm = 0 
        ALLOCATE ( savelh(ppsi), STAT=istat)
        savelh = 0 
        ALLOCATE ( savilh(ppsi), STAT=istat)
        savilh = 0 
        ALLOCATE ( rimp1(ppsi), STAT=istat)
        rimp1 = 0 
        ALLOCATE ( chiesec(ppsi), STAT=istat)
        chiesec = 0 
        ALLOCATE ( alphade(ppsi), STAT=istat)
        alphade = 0 
        ALLOCATE ( alphapr(ppsi), STAT=istat)
        alphapr = 0 
        ALLOCATE ( sighot(ppsi), STAT=istat)
        sighot = 0 
        ALLOCATE ( chiisec(ppsi), STAT=istat)
        chiisec = 0 
        ALLOCATE ( anheb(ppsi), STAT=istat)
        anheb = 0 
        ALLOCATE ( ajaveq(ppsi), STAT=istat)
        ajaveq = 0 
        ALLOCATE ( densum(ppsi), STAT=istat)
        densum = 0 
        ALLOCATE ( gja2(ppsi), STAT=istat)
        gja2 = 0 
        ALLOCATE ( rminora(ppsi), STAT=istat)
        rminora = 0 
        ALLOCATE ( rmajora(ppsi), STAT=istat)
        rmajora = 0 
        ALLOCATE ( elonga(ppsi), STAT=istat)
        elonga = 0 
        ALLOCATE ( ajave(ppsi), STAT=istat)
        ajave = 0 
        ALLOCATE ( ajbtsq(ppsi), STAT=istat)
        ajbtsq = 0 
        ALLOCATE ( ajbsq(ppsi), STAT=istat)
        ajbsq = 0 
        ALLOCATE ( qprof2(ppsi+1), STAT=istat)
        qprof2 = 0 
        ALLOCATE ( asv(ppsi,pneq), STAT=istat)
        asv = 0 
        ALLOCATE ( bsv(ppsi,pneq), STAT=istat)
        bsv = 0 
        ALLOCATE ( csv(ppsi,pneq), STAT=istat)
        csv = 0 
        ALLOCATE ( dsv(ppsi,pneq), STAT=istat)
        dsv = 0 
        ALLOCATE ( vgain(pncoil), STAT=istat)
        vgain = 0 
        ALLOCATE ( voltmax(pncoil), STAT=istat)
        voltmax = 0 
        ALLOCATE ( tramp(pncoil), STAT=istat)
        tramp = 0 
        ALLOCATE ( voltn(pncoil), STAT=istat)
        voltn = 0 
        ALLOCATE ( diold(pncoil), STAT=istat)
        diold = 0 
        ALLOCATE ( vgain2(pncoil), STAT=istat)
        vgain2 = 0 
        ALLOCATE ( rewire(pncoil), STAT=istat)
        rewire = 0 
        ALLOCATE ( diol2(pncoil), STAT=istat)
        diol2 = 0 
        ALLOCATE ( vgain3(pncoil), STAT=istat)
        vgain3 = 0 
        ALLOCATE ( thrumx(pncoil), STAT=istat)
        thrumx = 0 
        ALLOCATE ( thrtp(pncoil), STAT=istat)
        thrtp = 0 
        ALLOCATE ( thrtm(pncoil), STAT=istat)
        thrtm = 0 
        ALLOCATE ( thrur(pncoil), STAT=istat)
        thrur = 0 
        ALLOCATE ( thrps(pncoil), STAT=istat)
        thrps = 0 
        ALLOCATE ( vfeed(pncoil), STAT=istat)
        vfeed = 0 
        ALLOCATE ( save1(pncoil), STAT=istat)
        save1 = 0 
        ALLOCATE ( save2(pncoil), STAT=istat)
        save2 = 0 
        ALLOCATE ( save3(pncoil), STAT=istat)
        save3 = 0 
        ALLOCATE ( save4(pncoil), STAT=istat)
        save4 = 0 
        ALLOCATE ( save5(pncoil), STAT=istat)
        save5 = 0 
        ALLOCATE ( save6(pncoil), STAT=istat)
        save6 = 0 
        ALLOCATE ( thruc(pncoil), STAT=istat)
        thruc = 0 
        ALLOCATE ( x2ave(ppsi), STAT=istat)
        x2ave = 0 
        ALLOCATE ( cwirin(999), STAT=istat)
        cwirin = 0 
        ALLOCATE ( cwold(24), STAT=istat)
        cwold = 0 
        ALLOCATE ( gcursv(24), STAT=istat)
        gcursv = 0 
        ALLOCATE ( cdot(24), STAT=istat)
        cdot = 0 
        ALLOCATE ( gmary(24,24), STAT=istat)
        gmary = 0 
        ALLOCATE ( xrplate(pnplat), STAT=istat)
        xrplate = 0 
        ALLOCATE ( xlplate(pnplat), STAT=istat)
        xlplate = 0 
        ALLOCATE ( zrplate(pnplat), STAT=istat)
        zrplate = 0 
        ALLOCATE ( zlplate(pnplat), STAT=istat)
        zlplate = 0 
        ALLOCATE ( strike(pnplat,2), STAT=istat)
        strike = 0 
        ALLOCATE ( fplate(pnplat,2), STAT=istat)
        fplate = 0 
        ALLOCATE ( dsep(pnplat,2), STAT=istat)
        dsep = 0 
        ALLOCATE ( hplate(pnplat,pnseg), STAT=istat)
        hplate = 0 
        ALLOCATE ( dplate(pnplat,pnseg), STAT=istat)
        dplate = 0 
        ALLOCATE ( xsega(pnplat,pnseg+1), STAT=istat)
        xsega = 0 
        ALLOCATE ( zsega(pnplat,pnseg+1), STAT=istat)
        zsega = 0 
        ALLOCATE ( rsceg(pngroup), STAT=istat)
        rsceg = 0 
        ALLOCATE ( ceg(pngroup), STAT=istat)
        ceg = 0 
        ALLOCATE ( cegp1(pngroup), STAT=istat)
        cegp1 = 0 
        ALLOCATE ( cegm1(pngroup), STAT=istat)
        cegm1 = 0 
        ALLOCATE ( ceg0(pngroup), STAT=istat)
        ceg0 = 0 
        ALLOCATE ( ceg0m1(pngroup), STAT=istat)
        ceg0m1 = 0 
        ALLOCATE ( aintceg(pngroup), STAT=istat)
        aintceg = 0 
        ALLOCATE ( flxeg(pngroup), STAT=istat)
        flxeg = 0 
        ALLOCATE ( flxegm1(pngroup), STAT=istat)
        flxegm1 = 0 
        ALLOCATE ( flxegm2(pngroup), STAT=istat)
        flxegm2 = 0 
        ALLOCATE ( veg(pngroup), STAT=istat)
        veg = 0 
        ALLOCATE ( vegm1(pngroup), STAT=istat)
        vegm1 = 0 
        ALLOCATE ( aturneg(pngroup), STAT=istat)
        aturneg = 0 
        ALLOCATE ( voheg(pngroup), STAT=istat)
        voheg = 0 
        ALLOCATE ( vohegm1(pngroup), STAT=istat)
        vohegm1 = 0 
        ALLOCATE ( ceg0m2(pngroup), STAT=istat)
        ceg0m2 = 0 
        ALLOCATE ( teineg(pngroup), STAT=istat)
        teineg = 0 
        ALLOCATE ( tauseg(pngroup), STAT=istat)
        tauseg = 0 
        ALLOCATE ( gainpeg(pngroup), STAT=istat)
        gainpeg = 0 
        ALLOCATE ( gaindeg(pngroup), STAT=istat)
        gaindeg = 0 
        ALLOCATE ( gainieg(pngroup), STAT=istat)
        gainieg = 0 
        ALLOCATE ( vmineg(pngroup), STAT=istat)
        vmineg = 0 
        ALLOCATE ( vmaxeg(pngroup), STAT=istat)
        vmaxeg = 0 
        ALLOCATE ( dcur(pngroup), STAT=istat)
        dcur = 0 
        ALLOCATE ( dcurm1(pngroup), STAT=istat)
        dcurm1 = 0 
        ALLOCATE ( dcurm2(pngroup), STAT=istat)
        dcurm2 = 0 
        ALLOCATE ( vegplot(pncoil), STAT=istat)
        vegplot = 0 
        ALLOCATE ( gvolt(ptpts,pngroup), STAT=istat)
        gvolt = 0 
        ALLOCATE ( ameg(pngroup,pngroup), STAT=istat)
        ameg = 0 
        ALLOCATE ( ameginv(pngroup,pngroup), STAT=istat)
        ameginv = 0 
        ALLOCATE ( tempc(pncoil), STAT=istat)
        tempc = 0 
        ALLOCATE ( dxcoil(pncoil), STAT=istat)
        dxcoil = 0 
        ALLOCATE ( dzcoil(pncoil), STAT=istat)
        dzcoil = 0 
        ALLOCATE ( fcu(pncoil), STAT=istat)
        fcu = 0 
        ALLOCATE ( fss(pncoil), STAT=istat)
        fss = 0 
        ALLOCATE ( ccics(pncoil), STAT=istat)
        ccics = 0 
        ALLOCATE ( templ(pngroup), STAT=istat)
        templ = 0 
        ALLOCATE ( ufdata(2*pnsave,pnx,30), STAT=istat)
        ufdata = 0                                                         
        ALLOCATE ( chivolt(pnx,pnz), STAT=istat)
        chivolt = 0
        ALLOCATE ( lvltdiag(pnx,pnz), STAT=istat)
        lvltdiag = 0
        ALLOCATE ( obsdiag(2,pobs), STAT=istat)
        obsdiag = 0
      if (istat .ne. 0) then 
         print *, 'Allocation Error : alloc_clinam   ' 
         stop
      end if
            
      return
      END SUBROUTINE alloc_clinam  
