      SUBROUTINE alloc_tcvcom  
      
      USE TCVCOM
      
      IMPLICIT NONE
      INTEGER :: istat = 0 
      
        ALLOCATE ( ax(pnvvel,pnvvel+1), STAT=istat)
        ax = 0 
        ALLOCATE ( aph(pmmay), STAT=istat)
        aph = 0 
        ALLOCATE ( a7(pnfob,pnshap), STAT=istat)
        a7 = 0 
        ALLOCATE ( a8(pnfob,pnvvel), STAT=istat)
        a8 = 0 
        ALLOCATE ( a8l(pnob,pnvvel), STAT=istat)
        a8l = 0 
        ALLOCATE ( berr(pnprob), STAT=istat)
        berr = 0 
        ALLOCATE ( bee(pnprob), STAT=istat)
        bee = 0 
        ALLOCATE ( coth(pnprob), STAT=istat)
        coth = 0 
        ALLOCATE ( bxob(pnbob), STAT=istat)
        bxob = 0 
        ALLOCATE ( bzob(pnbob), STAT=istat)
        bzob = 0 
        ALLOCATE ( coesv(pnwire), STAT=istat)
        coesv = 0 
        ALLOCATE ( cerr(picur), STAT=istat)
        cerr = 0 
        ALLOCATE ( curr(picur), STAT=istat)
        curr = 0 
        ALLOCATE ( cx(pnvvel), STAT=istat)
        cx = 0 
        ALLOCATE ( cxold(pnvvel), STAT=istat)
        cxold = 0 
        ALLOCATE ( cxave(pnvvel), STAT=istat)
        cxave = 0 
        ALLOCATE ( cxold2(pnvvel), STAT=istat)
        cxold2 = 0 
        ALLOCATE ( dex(pnprob,picur), STAT=istat)
        dex = 0 
        ALLOCATE ( dep(pnprob,pmmay), STAT=istat)
        dep = 0 
        ALLOCATE ( dsh(pnx,pnz), STAT=istat)
        dsh = 0 
        ALLOCATE ( ddd(pnshap), STAT=istat)
        ddd = 0 
        ALLOCATE ( dddd(pnshap), STAT=istat)
        dddd = 0 
        ALLOCATE ( elss(pnshap,pnshap), STAT=istat)
        elss = 0 
        ALLOCATE ( elsv(pnshap,pnvvel), STAT=istat)
        elsv = 0 
        ALLOCATE ( elvvi(pnvvel,pnvvel), STAT=istat)
        elvvi = 0 
        ALLOCATE ( elvv(pnvvel,pnvvel), STAT=istat)
        elvv = 0 
        ALLOCATE ( eee(pnob), STAT=istat)
        eee = 0 
        ALLOCATE ( ffob(pnob), STAT=istat)
        ffob = 0 
        ALLOCATE ( ferr(pnluup), STAT=istat)
        ferr = 0 
        ALLOCATE ( flxa(pnluup), STAT=istat)
        flxa = 0 
        ALLOCATE ( flxo(pnluup), STAT=istat)
        flxo = 0 
        ALLOCATE ( flxd(pnluup), STAT=istat)
        flxd = 0 
        ALLOCATE ( gx(pnluup,picur), STAT=istat)
        gx = 0 
        ALLOCATE ( gp(pnluup,pmmay), STAT=istat)
        gp = 0 
        ALLOCATE ( hshap(pnshap), STAT=istat)
        hshap = 0 
        ALLOCATE ( hvvel(pnvvel), STAT=istat)
        hvvel = 0 
        ALLOCATE ( isvf(picur), STAT=istat)
        isvf = 0 
        ALLOCATE ( isvl(picur), STAT=istat)
        isvl = 0 
        ALLOCATE ( rhoa(pnob), STAT=istat)
        rhoa = 0 
        ALLOCATE ( rhoo(pnob), STAT=istat)
        rhoo = 0 
        ALLOCATE ( rho(pnob), STAT=istat)
        rho = 0 
        ALLOCATE ( rscurr(picur), STAT=istat)
        rscurr = 0 
        ALLOCATE ( rshap(pnshap), STAT=istat)
        rshap = 0 
        ALLOCATE ( wshap(pnshap), STAT=istat)
        wshap = 0 
        ALLOCATE ( zshap(pnshap), STAT=istat)
        zshap = 0 
        ALLOCATE ( rvvel(pnvvel), STAT=istat)
        rvvel = 0 
        ALLOCATE ( rhn(pnvvel), STAT=istat)
        rhn = 0 
        ALLOCATE ( wvvel(pnvvel), STAT=istat)
        wvvel = 0 
        ALLOCATE ( zvvel(pnvvel), STAT=istat)
        zvvel = 0 
        ALLOCATE ( sith(pnprob), STAT=istat)
        sith = 0 
        ALLOCATE ( thb(pnprob), STAT=istat)
        thb = 0 
        ALLOCATE ( vvv(pnprob), STAT=istat)
        vvv = 0 
        ALLOCATE ( xb(pnprob), STAT=istat)
        xb = 0 
        ALLOCATE ( zb(pnprob), STAT=istat)
        zb = 0 
        ALLOCATE ( volttcv(pnwire), STAT=istat)
        volttcv = 0 
        ALLOCATE ( umeg(pnob,pnshap), STAT=istat)
        umeg = 0 
        ALLOCATE ( www(pnluup), STAT=istat)
        www = 0 
        ALLOCATE ( xf(pnluup), STAT=istat)
        xf = 0 
        ALLOCATE ( zf(pnluup), STAT=istat)
        zf = 0 
        ALLOCATE ( xfob(pnfob), STAT=istat)
        xfob = 0 
        ALLOCATE ( zfob(pnfob), STAT=istat)
        zfob = 0 
        ALLOCATE ( xbxob(pnbob), STAT=istat)
        xbxob = 0 
        ALLOCATE ( xbzob(pnbob), STAT=istat)
        xbzob = 0 
        ALLOCATE ( zbxob(pnbob), STAT=istat)
        zbxob = 0 
        ALLOCATE ( zbzob(pnbob), STAT=istat)
        zbzob = 0 
        ALLOCATE ( xniv(pmmay,4), STAT=istat)
        xniv = 0 
        ALLOCATE ( zniv(pmmay), STAT=istat)
        zniv = 0 
        ALLOCATE ( xhnn(pmmay), STAT=istat)
        xhnn = 0 
        ALLOCATE ( zhnn(pmmay), STAT=istat)
        zhnn = 0 
        ALLOCATE ( xhne(pmmay), STAT=istat)
        xhne = 0 
        ALLOCATE ( xhoo(pmmay), STAT=istat)
        xhoo = 0 
        ALLOCATE ( zhoo(pmmay), STAT=istat)
        zhoo = 0 
        ALLOCATE ( xhee(pmmay), STAT=istat)
        xhee = 0 
        ALLOCATE ( xhss(pmmay), STAT=istat)
        xhss = 0 
        ALLOCATE ( zhss(pmmay), STAT=istat)
        zhss = 0 
        ALLOCATE ( xhse(pmmay), STAT=istat)
        xhse = 0                                                           
      if (istat .ne. 0) then 
         print *, 'Allocation Error : alloc_tcvcom   ' 
         stop
      end if
            
      return
      END SUBROUTINE alloc_tcvcom  
