      SUBROUTINE alloc_scr1  
      
      USE SCR1
      
      IMPLICIT NONE
      INTEGER :: istat = 0 
      
        ALLOCATE ( piz(pnz), STAT=istat)
        piz = 0 
        ALLOCATE ( wiz(pnz), STAT=istat)
        wiz = 0 
        ALLOCATE ( giz(pnz), STAT=istat)
        giz = 0 
        ALLOCATE ( uiz(pnz), STAT=istat)
        uiz = 0 
        ALLOCATE ( aiz(pnz), STAT=istat)
        aiz = 0 
        ALLOCATE ( pim(pnz), STAT=istat)
        pim = 0 
        ALLOCATE ( wim(pnz), STAT=istat)
        wim = 0 
        ALLOCATE ( gim(pnz), STAT=istat)
        gim = 0 
        ALLOCATE ( uim(pnz), STAT=istat)
        uim = 0 
        ALLOCATE ( aim(pnz), STAT=istat)
        aim = 0 
        ALLOCATE ( pip(pnz), STAT=istat)
        pip = 0 
        ALLOCATE ( wip(pnz), STAT=istat)
        wip = 0 
        ALLOCATE ( gip(pnz), STAT=istat)
        gip = 0 
        ALLOCATE ( uip(pnz), STAT=istat)
        uip = 0 
        ALLOCATE ( abip(pnz), STAT=istat)
        abip = 0 
        ALLOCATE ( biz(pnz), STAT=istat)
        biz = 0 
        ALLOCATE ( bim(pnz), STAT=istat)
        bim = 0 
        ALLOCATE ( bip(pnz), STAT=istat)
        bip = 0 
        ALLOCATE ( rim(pnz), STAT=istat)
        rim = 0 
        ALLOCATE ( riz(pnz), STAT=istat)
        riz = 0 
        ALLOCATE ( rip(pnz), STAT=istat)
        rip = 0 
        ALLOCATE ( qim(pnz), STAT=istat)
        qim = 0 
        ALLOCATE ( qiz(pnz), STAT=istat)
        qiz = 0 
        ALLOCATE ( qip(pnz), STAT=istat)
        qip = 0 
        ALLOCATE ( abouna(pnz), STAT=istat)
        abouna = 0 
        ALLOCATE ( abounb(pnz), STAT=istat)
        abounb = 0 
        ALLOCATE ( abounc(pnz), STAT=istat)
        abounc = 0 
        ALLOCATE ( abound(pnz), STAT=istat)
        abound = 0 
        ALLOCATE ( qt2(pnz), STAT=istat)
        qt2 = 0 
        ALLOCATE ( qt4(pnz), STAT=istat)
        qt4 = 0 
        ALLOCATE ( qt(pnz), STAT=istat)
        qt = 0 
        ALLOCATE ( fac7(pnz), STAT=istat)
        fac7 = 0 
        ALLOCATE ( term3a(pnz), STAT=istat)
        term3a = 0 
        ALLOCATE ( term4(pnz), STAT=istat)
        term4 = 0 
        ALLOCATE ( term5(pnz), STAT=istat)
        term5 = 0 
        ALLOCATE ( term6(pnz), STAT=istat)
        term6 = 0 
        ALLOCATE ( term8(pnz), STAT=istat)
        term8 = 0 
        ALLOCATE ( rt(pnz), STAT=istat)
        rt = 0 
        ALLOCATE ( term9(pnz), STAT=istat)
        term9 = 0 
        ALLOCATE ( fac7a(pnz), STAT=istat)
        fac7a = 0 
        ALLOCATE ( wf1pa(pnz), STAT=istat)
        wf1pa = 0 
        ALLOCATE ( gf1pa(pnz), STAT=istat)
        gf1pa = 0 
        ALLOCATE ( uf1pa(pnz), STAT=istat)
        uf1pa = 0 
        ALLOCATE ( bf1pa(pnz), STAT=istat)
        bf1pa = 0 
        ALLOCATE ( rf1pa(pnz), STAT=istat)
        rf1pa = 0 
        ALLOCATE ( qf1pa(pnz), STAT=istat)
        qf1pa = 0 
        ALLOCATE ( wf2pa(pnz), STAT=istat)
        wf2pa = 0 
        ALLOCATE ( gf2pa(pnz), STAT=istat)
        gf2pa = 0 
        ALLOCATE ( uf2pa(pnz), STAT=istat)
        uf2pa = 0 
        ALLOCATE ( bf2pa(pnz), STAT=istat)
        bf2pa = 0 
        ALLOCATE ( rf2pa(pnz), STAT=istat)
        rf2pa = 0 
        ALLOCATE ( qf2pa(pnz), STAT=istat)
        qf2pa = 0 
        ALLOCATE ( wf1ta(pnz), STAT=istat)
        wf1ta = 0 
        ALLOCATE ( gf1ta(pnz), STAT=istat)
        gf1ta = 0 
        ALLOCATE ( uf1ta(pnz), STAT=istat)
        uf1ta = 0 
        ALLOCATE ( bf1ta(pnz), STAT=istat)
        bf1ta = 0 
        ALLOCATE ( rf1ta(pnz), STAT=istat)
        rf1ta = 0 
        ALLOCATE ( qf1ta(pnz), STAT=istat)
        qf1ta = 0 
        ALLOCATE ( dpara(pnz), STAT=istat)
        dpara = 0 
        ALLOCATE ( dparb(pnz), STAT=istat)
        dparb = 0 
        ALLOCATE ( dparc(pnz), STAT=istat)
        dparc = 0 
        ALLOCATE ( dpard(pnz), STAT=istat)
        dpard = 0 
        ALLOCATE ( ajp2(pnx,pnz), STAT=istat)
        ajp2 = 0 
        ALLOCATE ( utsave(pnx,pnz), STAT=istat)
        utsave = 0 
        ALLOCATE ( rjcdg(pnx,pnz), STAT=istat)
        rjcdg = 0 
        ALLOCATE ( gapr(pngroup), STAT=istat)
        gapr = 0 
        ALLOCATE ( gapi(pngroup), STAT=istat)
        gapi = 0 
        ALLOCATE ( gapv(pngroup), STAT=istat)
        gapv = 0 
        ALLOCATE ( pling1(pnx,pnz), STAT=istat)
        pling1 = 0 
        ALLOCATE ( pling2(pnx,pnz), STAT=istat)
        pling2 = 0 
        ALLOCATE ( pling3(pnx,pnz), STAT=istat)
        pling3 = 0 
        ALLOCATE ( pling4(pnx,pnz), STAT=istat)
        pling4 = 0 
        ALLOCATE ( gling1(pnx,pnz), STAT=istat)
        gling1 = 0 
        ALLOCATE ( gling2(pnx,pnz), STAT=istat)
        gling2 = 0 
        ALLOCATE ( gling3(pnx,pnz), STAT=istat)
        gling3 = 0 
        ALLOCATE ( pling5(pnx,pnz), STAT=istat)
        pling5 = 0 
        ALLOCATE ( ajp3(pnx,pnz), STAT=istat)
        ajp3 = 0 
        ALLOCATE ( ajp4(pnx,pnz), STAT=istat)
        ajp4 = 0                                                           
      if (istat .ne. 0) then 
         print *, 'Allocation Error : alloc_scr1   ' 
         stop
      end if
            
      return
      END SUBROUTINE alloc_scr1  
