      SUBROUTINE dealloc_tcvcom  
      
      USE TCVCOM
      
      IMPLICIT NONE
      INTEGER :: istat = 0 
      
        DEALLOCATE ( ax, STAT=istat)
        DEALLOCATE ( aph, STAT=istat)
        DEALLOCATE ( a7, STAT=istat)
        DEALLOCATE ( a8, STAT=istat)
        DEALLOCATE ( a8l, STAT=istat)
        DEALLOCATE ( berr, STAT=istat)
        DEALLOCATE ( bee, STAT=istat)
        DEALLOCATE ( coth, STAT=istat)
        DEALLOCATE ( bxob, STAT=istat)
        DEALLOCATE ( bzob, STAT=istat)
        DEALLOCATE ( coesv, STAT=istat)
        DEALLOCATE ( cerr, STAT=istat)
        DEALLOCATE ( curr, STAT=istat)
        DEALLOCATE ( cx, STAT=istat)
        DEALLOCATE ( cxold, STAT=istat)
        DEALLOCATE ( cxave, STAT=istat)
        DEALLOCATE ( cxold2, STAT=istat)
        DEALLOCATE ( dex, STAT=istat)
        DEALLOCATE ( dep, STAT=istat)
        DEALLOCATE ( dsh, STAT=istat)
        DEALLOCATE ( ddd, STAT=istat)
        DEALLOCATE ( dddd, STAT=istat)
        DEALLOCATE ( elss, STAT=istat)
        DEALLOCATE ( elsv, STAT=istat)
        DEALLOCATE ( elvvi, STAT=istat)
        DEALLOCATE ( elvv, STAT=istat)
        DEALLOCATE ( eee, STAT=istat)
        DEALLOCATE ( ffob, STAT=istat)
        DEALLOCATE ( ferr, STAT=istat)
        DEALLOCATE ( flxa, STAT=istat)
        DEALLOCATE ( flxo, STAT=istat)
        DEALLOCATE ( flxd, STAT=istat)
        DEALLOCATE ( gx, STAT=istat)
        DEALLOCATE ( gp, STAT=istat)
        DEALLOCATE ( hshap, STAT=istat)
        DEALLOCATE ( hvvel, STAT=istat)
        DEALLOCATE ( isvf, STAT=istat)
        DEALLOCATE ( isvl, STAT=istat)
        DEALLOCATE ( rhoa, STAT=istat)
        DEALLOCATE ( rhoo, STAT=istat)
        DEALLOCATE ( rho, STAT=istat)
        DEALLOCATE ( rscurr, STAT=istat)
        DEALLOCATE ( rshap, STAT=istat)
        DEALLOCATE ( wshap, STAT=istat)
        DEALLOCATE ( zshap, STAT=istat)
        DEALLOCATE ( rvvel, STAT=istat)
        DEALLOCATE ( rhn, STAT=istat)
        DEALLOCATE ( wvvel, STAT=istat)
        DEALLOCATE ( zvvel, STAT=istat)
        DEALLOCATE ( sith, STAT=istat)
        DEALLOCATE ( thb, STAT=istat)
        DEALLOCATE ( vvv, STAT=istat)
        DEALLOCATE ( xb, STAT=istat)
        DEALLOCATE ( zb, STAT=istat)
        DEALLOCATE ( volttcv, STAT=istat)
        DEALLOCATE ( umeg, STAT=istat)
        DEALLOCATE ( www, STAT=istat)
        DEALLOCATE ( xf, STAT=istat)
        DEALLOCATE ( zf, STAT=istat)
        DEALLOCATE ( xfob, STAT=istat)
        DEALLOCATE ( zfob, STAT=istat)
        DEALLOCATE ( xbxob, STAT=istat)
        DEALLOCATE ( xbzob, STAT=istat)
        DEALLOCATE ( zbxob, STAT=istat)
        DEALLOCATE ( zbzob, STAT=istat)
        DEALLOCATE ( xniv, STAT=istat)
        DEALLOCATE ( zniv, STAT=istat)
        DEALLOCATE ( xhnn, STAT=istat)
        DEALLOCATE ( zhnn, STAT=istat)
        DEALLOCATE ( xhne, STAT=istat)
        DEALLOCATE ( xhoo, STAT=istat)
        DEALLOCATE ( zhoo, STAT=istat)
        DEALLOCATE ( xhee, STAT=istat)
        DEALLOCATE ( xhss, STAT=istat)
        DEALLOCATE ( zhss, STAT=istat)
        DEALLOCATE ( xhse, STAT=istat)
     
      if (istat .ne. 0) then 
         print *, 'Deallocation Error : alloc_tcvcom   ' 
      end if
            
      return
      END SUBROUTINE dealloc_tcvcom  
