      SUBROUTINE dealloc_scr1  
      
      USE SCR1
      
      IMPLICIT NONE
      INTEGER :: istat = 0 
      
        DEALLOCATE ( piz, STAT=istat)
        DEALLOCATE ( wiz, STAT=istat)
        DEALLOCATE ( giz, STAT=istat)
        DEALLOCATE ( uiz, STAT=istat)
        DEALLOCATE ( aiz, STAT=istat)
        DEALLOCATE ( pim, STAT=istat)
        DEALLOCATE ( wim, STAT=istat)
        DEALLOCATE ( gim, STAT=istat)
        DEALLOCATE ( uim, STAT=istat)
        DEALLOCATE ( aim, STAT=istat)
        DEALLOCATE ( pip, STAT=istat)
        DEALLOCATE ( wip, STAT=istat)
        DEALLOCATE ( gip, STAT=istat)
        DEALLOCATE ( uip, STAT=istat)
        DEALLOCATE ( abip, STAT=istat)
        DEALLOCATE ( biz, STAT=istat)
        DEALLOCATE ( bim, STAT=istat)
        DEALLOCATE ( bip, STAT=istat)
        DEALLOCATE ( rim, STAT=istat)
        DEALLOCATE ( riz, STAT=istat)
        DEALLOCATE ( rip, STAT=istat)
        DEALLOCATE ( qim, STAT=istat)
        DEALLOCATE ( qiz, STAT=istat)
        DEALLOCATE ( qip, STAT=istat)
        DEALLOCATE ( abouna, STAT=istat)
        DEALLOCATE ( abounb, STAT=istat)
        DEALLOCATE ( abounc, STAT=istat)
        DEALLOCATE ( abound, STAT=istat)
        DEALLOCATE ( qt2, STAT=istat)
        DEALLOCATE ( qt4, STAT=istat)
        DEALLOCATE ( qt, STAT=istat)
        DEALLOCATE ( fac7, STAT=istat)
        DEALLOCATE ( term3a, STAT=istat)
        DEALLOCATE ( term4, STAT=istat)
        DEALLOCATE ( term5, STAT=istat)
        DEALLOCATE ( term6, STAT=istat)
        DEALLOCATE ( term8, STAT=istat)
        DEALLOCATE ( rt, STAT=istat)
        DEALLOCATE ( term9, STAT=istat)
        DEALLOCATE ( fac7a, STAT=istat)
        DEALLOCATE ( wf1pa, STAT=istat)
        DEALLOCATE ( gf1pa, STAT=istat)
        DEALLOCATE ( uf1pa, STAT=istat)
        DEALLOCATE ( bf1pa, STAT=istat)
        DEALLOCATE ( rf1pa, STAT=istat)
        DEALLOCATE ( qf1pa, STAT=istat)
        DEALLOCATE ( wf2pa, STAT=istat)
        DEALLOCATE ( gf2pa, STAT=istat)
        DEALLOCATE ( uf2pa, STAT=istat)
        DEALLOCATE ( bf2pa, STAT=istat)
        DEALLOCATE ( rf2pa, STAT=istat)
        DEALLOCATE ( qf2pa, STAT=istat)
        DEALLOCATE ( wf1ta, STAT=istat)
        DEALLOCATE ( gf1ta, STAT=istat)
        DEALLOCATE ( uf1ta, STAT=istat)
        DEALLOCATE ( bf1ta, STAT=istat)
        DEALLOCATE ( rf1ta, STAT=istat)
        DEALLOCATE ( qf1ta, STAT=istat)
        DEALLOCATE ( dpara, STAT=istat)
        DEALLOCATE ( dparb, STAT=istat)
        DEALLOCATE ( dparc, STAT=istat)
        DEALLOCATE ( dpard, STAT=istat)
        DEALLOCATE ( ajp2, STAT=istat)
        DEALLOCATE ( utsave, STAT=istat)
        DEALLOCATE ( rjcdg, STAT=istat)
        DEALLOCATE ( gapr, STAT=istat)
        DEALLOCATE ( gapi, STAT=istat)
        DEALLOCATE ( gapv, STAT=istat)
        DEALLOCATE ( pling1, STAT=istat)
        DEALLOCATE ( pling2, STAT=istat)
        DEALLOCATE ( pling3, STAT=istat)
        DEALLOCATE ( pling4, STAT=istat)
        DEALLOCATE ( gling1, STAT=istat)
        DEALLOCATE ( gling2, STAT=istat)
        DEALLOCATE ( gling3, STAT=istat)
        DEALLOCATE ( pling5, STAT=istat)
        DEALLOCATE ( ajp3, STAT=istat)
        DEALLOCATE ( ajp4, STAT=istat)
     
      if (istat .ne. 0) then 
         print *, 'Deallocation Error : alloc_scr1   ' 
      end if
            
      return
      END SUBROUTINE dealloc_scr1  
