      MODULE LOOP1
      IMPLICIT NONE

      REAL*8 :: PSF2A,PSF4A,PSF5A,PSF6NA,PSF8A,PSF1B,PSF2B,PSF3B,PSF4B,  &  
     &          PSF5B,PSF6NB,PSF8B,PSF9B,PSI7A,PSF6FA,PSI7B,PSF6FB

      END MODULE LOOP1
