      MODULE PROBE1
      IMPLICIT NONE

      REAL*8 :: AMPI9A ,AMPI67A ,AMPI6FA ,AMPI66M ,AMPI6FB ,AMPI67B ,    &  
     &          AMPI7FB ,AMPI9B ,AMPI89B ,AMPI8B ,AMPI4B ,AMPI3B ,       &  
     &          AMPI2B ,AMPI1B ,AMPI11M ,AMPI1A ,AMPI2A ,AMPI5A

      END MODULE PROBE1
