      subroutine pelkut(rps,tes,dens,imppelx,trmpel,dndt)
!
!******************************************************************************
!***********************************************************************
!*****PELKUTIM determines the pellet impurity ablation rate using a fit*
!*****generated by Kuteev.  Added by L.R. Baylor                       *
!*****References:                                                      *
!*****Kuteev, Nucl Fusion 1167 (1995).                                 *
!*****Input:                                                           *
!*****tolplr-tolerance for fractional radius of pellet remaining.      *
!*****rps-pellet radius-m.                                             *
!*****tes-electron temperature-keV.                                    *
!*****dens-electron density-/m**3.                                     *
!*****Output:                                                          *
!*****rdot-rate of change in pellet radius-m/s.                        *
!***********************************************************************
!============
! idecl:  explicitize implicit INTEGER declarations:
      IMPLICIT NONE
      INTEGER, PARAMETER :: R8=SELECTED_REAL_KIND(12,100)
      INTEGER imppelx
!============
! idecl:  explicitize implicit REAL declarations:
      REAL*8 tes,dens,trmpel,dndt,rps,tesmin,amupne,amupkr,amupd2
      REAL*8 pi,denmne,denmkr,denmd2,tolplr,avn,denm,amup,factor
      REAL*8 tinf,rpcm,dninf
!============
      data tesmin/   1.0_R8/
      data amupne / 20.18_R8/
      data amupkr / 83.80_R8/
      data amupd2 / 2 /
      data pi / 3.14159_R8/
      data denmne / 1.205E3_R8/
      data denmkr / 2.155E3_R8/
      data denmd2 / 197.9_R8/
      data tolplr / 1.E-6_R8/
      data avn / 6.023E26_R8/
!
!
!     factor = 3.015e15        !Argon
!     factor = 7.63e14         !Carbon
!
      if(imppelx.eq.5) then
      denm = denmne
      amup = amupne
      factor = 5.066E15_R8
                endif
!
      if(imppelx.eq.6) then
      denm = denmkr
      amup = amupkr
      factor = 2.043E15_R8
                      endif
      if(imppelx.eq.0) then
      denm = denmd2
      amup = amupd2
      factor = 1.12E16_R8
               endif
      trmpel = 4._R8*pi*denm*avn/(3._R8*amup)
!*****Check pellet size and minimum electron temperature.
      if((rps.lt.(tolplr)).or.(tes.lt.tesmin)) then
      dndt = 0.0_R8
!        rdot = 0.0
      return
      endif
!*****Convert to Kuteev's units of cm and eV.
      tinf=tes
      rpcm=rps*1.0E2_R8
      dninf=dens*1.0E-6_R8
!*****Compute the ablation rate, dndt, in atoms/s.
      dndt=factor                                                        &  
     &      *tinf**(1.64)*dninf**(0.333)*rpcm**(1.333)*amup**(-0.333)
!*****Compute dr/dt in m/s.
!      rdot=-(dndt/(denm*4.0*pi*rps**2))*(amup/avn)
      return
      end
! 15Apr2005 fgtok -s r8_precision.sub "r8con.csh conversion"
