module trdatbuf_obj_tsc
  !
  ! **generated by gensis_f90.py -- do not edit!
  !
  ! module to define the trdatbuf data type -- container variable
  !    for trdat data (transp physics input data -- diagnostic, measured data)
  !
  ! only a data type is defined here...
 
  integer, parameter, private :: MIMPS = 5
  integer, parameter, private :: MIMPT = 100
 
  type trdatbuf
 
    real*8, dimension(:), pointer :: DATBUF
    integer :: LAIMPS
    integer :: LAIMPX
    integer :: LBX(8)
    integer :: LDATALP
    integer :: LDATBDI
    integer :: LDATCUR
    integer :: LDATDFL
    integer :: LDATDTG
    integer :: LDATDTX
    integer :: LDATEDI
    integer :: LDATEHP
    integer :: LDATELI
    integer :: LDATFIE
    integer :: LDATFMN
    integer :: LDATFMX
    integer :: LDATGAS
    integer :: LDATGF3
    integer :: LDATGF4
    integer :: LDATGF6
    integer :: LDATGFD
    integer :: LDATGFH
    integer :: LDATGFT
    integer :: LDATGIE
    integer :: LDATHAL
    integer :: LDATIBM
    integer :: LDATIEC
    integer :: LDATIIC
    integer :: LDATILH
    integer :: LDATL2B
    integer :: LDATLAD
    integer :: LDATLID
    integer :: LDATNTX
    integer :: LDATPBE
    integer :: LDATPBI
    integer :: LDATPEB
    integer :: LDATPEC
    integer :: LDATPFH
    integer :: LDATPFL
    integer :: LDATPIB
    integer :: LDATPIC
    integer :: LDATPLF
    integer :: LDATPLH
    integer :: LDATPOS
    integer :: LDATRBZ
    integer :: LDATRC3
    integer :: LDATRC4
    integer :: LDATRC6
    integer :: LDATRCD
    integer :: LDATRCH
    integer :: LDATRCT
    integer :: LDATRCY
    integer :: LDATRMN
    integer :: LDATRTP
    integer :: LDATSBT
    integer :: LDATSF3
    integer :: LDATSFA
    integer :: LDATSFL
    integer :: LDATSFP
    integer :: LDATSFT
    integer :: LDATTET
    integer :: LDATTIT
    integer :: LDATTPI
    integer :: LDATTQT
    integer :: LDATTRF
    integer :: LDATTXI
    integer :: LDATVPH
    integer :: LDATVSB
    integer :: LDATVSF
    integer :: LDATXKF
    integer :: LDATZEF
    integer :: LDATZFA
    integer :: LDATZIM
    integer :: LDATZPL
    integer :: LDMDF
    integer :: LDMFR
    integer :: LDMMX
    integer :: LDMSE
    integer :: LFBOL
    integer :: LFBPA
    integer :: LFBPB
    integer :: LFD2F
    integer :: LFDE2
    integer :: LFDF3
    integer :: LFDF4
    integer :: LFDF6
    integer :: LFDFD
    integer :: LFDFH
    integer :: LFDFT
    integer :: LFECF
    integer :: LFGRB
    integer :: LFIBE
    integer :: LFIBI
    integer :: LFJBM
    integer :: LFJEC
    integer :: LFJIC
    integer :: LFKE2
    integer :: LFKF2
    integer :: LFKI2
    integer :: LFKPH
    integer :: LFLF3
    integer :: LFLF4
    integer :: LFLF6
    integer :: LFLFD
    integer :: LFLFH
    integer :: LFLFT
    integer :: LFLHE
    integer :: LFLHJ
    integer :: LFMSE
    integer :: LFNER
    integer :: LFNI3
    integer :: LFNI4
    integer :: LFNI6
    integer :: LFNID
    integer :: LFNIH
    integer :: LFNIM
    integer :: LFNIT
    integer :: LFNMR
    integer :: LFOMG
    integer :: LFPRS
    integer :: LFQBE
    integer :: LFQBI
    integer :: LFQEC
    integer :: LFQIC
    integer :: LFQPR
    integer :: LFREE
    integer :: LFREE_W
    integer :: LFRES
    integer :: LFRQRFF
    integer :: LFSBI
    integer :: LFSIM(MIMPT)
    integer :: LFSYBOL
    integer :: LFSYBPA
    integer :: LFSYBPB
    integer :: LFSYD2F
    integer :: LFSYDE2
    integer :: LFSYDF3
    integer :: LFSYDF4
    integer :: LFSYDF6
    integer :: LFSYDFD
    integer :: LFSYDFH
    integer :: LFSYDFT
    integer :: LFSYECF
    integer :: LFSYGRB
    integer :: LFSYIBE
    integer :: LFSYIBI
    integer :: LFSYJBM
    integer :: LFSYJEC
    integer :: LFSYJIC
    integer :: LFSYKE2
    integer :: LFSYKF2
    integer :: LFSYKI2
    integer :: LFSYKPH
    integer :: LFSYLF3
    integer :: LFSYLF4
    integer :: LFSYLF6
    integer :: LFSYLFD
    integer :: LFSYLFH
    integer :: LFSYLFT
    integer :: LFSYLHE
    integer :: LFSYLHJ
    integer :: LFSYMSE
    integer :: LFSYNER
    integer :: LFSYNI3
    integer :: LFSYNI4
    integer :: LFSYNI6
    integer :: LFSYNID
    integer :: LFSYNIH
    integer :: LFSYNIM
    integer :: LFSYNIT
    integer :: LFSYNMR
    integer :: LFSYOMG
    integer :: LFSYPRS
    integer :: LFSYQBE
    integer :: LFSYQBI
    integer :: LFSYQEC
    integer :: LFSYQIC
    integer :: LFSYQPR
    integer :: LFSYRES
    integer :: LFSYSBI
    integer :: LFSYSIM(MIMPT)
    integer :: LFSYTER
    integer :: LFSYTI2
    integer :: LFSYTQI
    integer :: LFSYVB2
    integer :: LFSYVC3
    integer :: LFSYVC4
    integer :: LFSYVC6
    integer :: LFSYVCD
    integer :: LFSYVCH
    integer :: LFSYVCT
    integer :: LFSYVP2
    integer :: LFSYVPO
    integer :: LFSYVPR
    integer :: LFSYVTR
    integer :: LFSYZF2
    integer :: LFTER
    integer :: LFTI2
    integer :: LFTQI
    integer :: LFULNB
    integer :: LFVB2
    integer :: LFVC3
    integer :: LFVC4
    integer :: LFVC6
    integer :: LFVCD
    integer :: LFVCH
    integer :: LFVCT
    integer :: LFVP2
    integer :: LFVPO
    integer :: LFVPR
    integer :: LFVTR
    integer :: LFZF2
    integer :: LHLFNB
    integer :: LMOMD
    integer :: LPHSLH
    integer :: LPMDF
    integer :: LPMSE
    integer :: LPWREC
    integer :: LPWRLH
    integer :: LPWRNB
    integer :: LPWRRF
    integer :: LRMFR
    integer :: LRMP_BDY1
    integer :: LRMP_BDY2
    integer :: LRMSE
    integer :: LRPL
    integer :: LSSYBOL
    integer :: LSSYBPA
    integer :: LSSYBPB
    integer :: LSSYD2F
    integer :: LSSYDE2
    integer :: LSSYDF3
    integer :: LSSYDF4
    integer :: LSSYDF6
    integer :: LSSYDFD
    integer :: LSSYDFH
    integer :: LSSYDFT
    integer :: LSSYECF
    integer :: LSSYGRB
    integer :: LSSYIBE
    integer :: LSSYIBI
    integer :: LSSYJBM
    integer :: LSSYJEC
    integer :: LSSYJIC
    integer :: LSSYKE2
    integer :: LSSYKF2
    integer :: LSSYKI2
    integer :: LSSYKPH
    integer :: LSSYLF3
    integer :: LSSYLF4
    integer :: LSSYLF6
    integer :: LSSYLFD
    integer :: LSSYLFH
    integer :: LSSYLFT
    integer :: LSSYLHE
    integer :: LSSYLHJ
    integer :: LSSYMSE
    integer :: LSSYNER
    integer :: LSSYNI3
    integer :: LSSYNI4
    integer :: LSSYNI6
    integer :: LSSYNID
    integer :: LSSYNIH
    integer :: LSSYNIM
    integer :: LSSYNIT
    integer :: LSSYNMR
    integer :: LSSYOMG
    integer :: LSSYPRS
    integer :: LSSYQBE
    integer :: LSSYQBI
    integer :: LSSYQEC
    integer :: LSSYQIC
    integer :: LSSYQPR
    integer :: LSSYRES
    integer :: LSSYSBI
    integer :: LSSYSIM(MIMPT)
    integer :: LSSYTER
    integer :: LSSYTI2
    integer :: LSSYTQI
    integer :: LSSYVB2
    integer :: LSSYVC3
    integer :: LSSYVC4
    integer :: LSSYVC6
    integer :: LSSYVCD
    integer :: LSSYVCH
    integer :: LSSYVCT
    integer :: LSSYVP2
    integer :: LSSYVPO
    integer :: LSSYVPR
    integer :: LSSYVTR
    integer :: LSSYZF2
    integer :: LTIME1
    integer :: LTIME2
    integer :: LTIMEC
    integer :: LTIMLH
    integer :: LTIMNB
    integer :: LTIMRF
    integer :: LTIMRFF
    integer :: LTSAW
    integer :: LVLTNB
    integer :: LXBOL
    integer :: LXBPA
    integer :: LXBPB
    integer :: LXD2F
    integer :: LXDE2
    integer :: LXDF3
    integer :: LXDF4
    integer :: LXDF6
    integer :: LXDFD
    integer :: LXDFH
    integer :: LXDFT
    integer :: LXECF
    integer :: LXGRB
    integer :: LXIBE
    integer :: LXIBI
    integer :: LXJBM
    integer :: LXJEC
    integer :: LXJIC
    integer :: LXKE2
    integer :: LXKF2
    integer :: LXKI2
    integer :: LXKPH
    integer :: LXLF3
    integer :: LXLF4
    integer :: LXLF6
    integer :: LXLFD
    integer :: LXLFH
    integer :: LXLFT
    integer :: LXLHE
    integer :: LXLHJ
    integer :: LXMMX
    integer :: LXMSE
    integer :: LXNER
    integer :: LXNI3
    integer :: LXNI4
    integer :: LXNI6
    integer :: LXNID
    integer :: LXNIH
    integer :: LXNIM
    integer :: LXNIT
    integer :: LXNMR
    integer :: LXOMG
    integer :: LXPRS
    integer :: LXQBE
    integer :: LXQBI
    integer :: LXQEC
    integer :: LXQIC
    integer :: LXQPR
    integer :: LXRES
    integer :: LXRPL
    integer :: LXSBI
    integer :: LXSIM(MIMPS)
    integer :: LXSYBOL
    integer :: LXSYBPA
    integer :: LXSYBPB
    integer :: LXSYD2F
    integer :: LXSYDE2
    integer :: LXSYDF3
    integer :: LXSYDF4
    integer :: LXSYDF6
    integer :: LXSYDFD
    integer :: LXSYDFH
    integer :: LXSYDFT
    integer :: LXSYECF
    integer :: LXSYGRB
    integer :: LXSYIBE
    integer :: LXSYIBI
    integer :: LXSYJBM
    integer :: LXSYJEC
    integer :: LXSYJIC
    integer :: LXSYKE2
    integer :: LXSYKF2
    integer :: LXSYKI2
    integer :: LXSYKPH
    integer :: LXSYLF3
    integer :: LXSYLF4
    integer :: LXSYLF6
    integer :: LXSYLFD
    integer :: LXSYLFH
    integer :: LXSYLFT
    integer :: LXSYLHE
    integer :: LXSYLHJ
    integer :: LXSYMSE
    integer :: LXSYNER
    integer :: LXSYNI3
    integer :: LXSYNI4
    integer :: LXSYNI6
    integer :: LXSYNID
    integer :: LXSYNIH
    integer :: LXSYNIM
    integer :: LXSYNIT
    integer :: LXSYNMR
    integer :: LXSYOMG
    integer :: LXSYPRS
    integer :: LXSYQBE
    integer :: LXSYQBI
    integer :: LXSYQEC
    integer :: LXSYQIC
    integer :: LXSYQPR
    integer :: LXSYRES
    integer :: LXSYSBI
    integer :: LXSYSIM(MIMPS)
    integer :: LXSYTER
    integer :: LXSYTI2
    integer :: LXSYTQI
    integer :: LXSYVB2
    integer :: LXSYVC3
    integer :: LXSYVC4
    integer :: LXSYVC6
    integer :: LXSYVCD
    integer :: LXSYVCH
    integer :: LXSYVCT
    integer :: LXSYVP2
    integer :: LXSYVPO
    integer :: LXSYVPR
    integer :: LXSYVTR
    integer :: LXSYZF2
    integer :: LXTER
    integer :: LXTI2
    integer :: LXTQI
    integer :: LXVB2
    integer :: LXVC3
    integer :: LXVC4
    integer :: LXVC6
    integer :: LXVCD
    integer :: LXVCH
    integer :: LXVCT
    integer :: LXVP2
    integer :: LXVPO
    integer :: LXVPR
    integer :: LXVTR
    integer :: LXZF2
    integer :: LXZIMPS
    integer :: LXZIMPX
    integer :: LXZIMPXS
    integer :: LYRPL
    integer :: LYSIM
    integer :: MMAX
    integer :: NANTECH_D
    integer :: NANTICH_D
    integer :: NANTLH_D
    integer :: NBDATA
    integer :: NBX(8)
    integer :: NDMDF
    integer :: NDMFR
    integer :: NDMMX
    integer :: NDMSE
    integer :: NFRBCODE
    integer :: NFRBMODE
    integer :: NHECFT
    integer :: NHFMX
    integer :: NIMDF
    integer :: NISSIM(MIMPT)
    integer :: NISX(MIMPT)
    integer :: NITSIM(MIMPS)
    integer :: NITX(MIMPS)
    integer :: NMAPSIM(MIMPT)
    integer :: NMDXKF
    integer :: NMIMP
    integer :: NMOMD
    integer :: NNSIM
    integer :: NPMDF
    integer :: NPMSE
    integer :: NRHIS
    integer :: NRHIX
    integer :: NRIBOL
    integer :: NRIBPA
    integer :: NRIBPB
    integer :: NRID2F
    integer :: NRIDE2
    integer :: NRIDF3
    integer :: NRIDF4
    integer :: NRIDF6
    integer :: NRIDFD
    integer :: NRIDFH
    integer :: NRIDFT
    integer :: NRIECF
    integer :: NRIGRB
    integer :: NRIIBE
    integer :: NRIIBI
    integer :: NRIJBM
    integer :: NRIJEC
    integer :: NRIJIC
    integer :: NRIKE2
    integer :: NRIKF2
    integer :: NRIKI2
    integer :: NRIKPH
    integer :: NRILF3
    integer :: NRILF4
    integer :: NRILF6
    integer :: NRILFD
    integer :: NRILFH
    integer :: NRILFT
    integer :: NRILHE
    integer :: NRILHJ
    integer :: NRIMSE
    integer :: NRINER
    integer :: NRINI3
    integer :: NRINI4
    integer :: NRINI6
    integer :: NRINID
    integer :: NRINIH
    integer :: NRINIM
    integer :: NRINIT
    integer :: NRINMR
    integer :: NRIOMG
    integer :: NRIPRS
    integer :: NRIQBE
    integer :: NRIQBI
    integer :: NRIQEC
    integer :: NRIQIC
    integer :: NRIQPR
    integer :: NRIRES
    integer :: NRISBI
    integer :: NRISIM(MIMPS)
    integer :: NRITER
    integer :: NRITI2
    integer :: NRITQI
    integer :: NRIVB2
    integer :: NRIVC3
    integer :: NRIVC4
    integer :: NRIVC6
    integer :: NRIVCD
    integer :: NRIVCH
    integer :: NRIVCT
    integer :: NRIVP2
    integer :: NRIVPO
    integer :: NRIVPR
    integer :: NRIVTR
    integer :: NRIZF2
    integer :: NRMFR
    integer :: NRMSE
    integer :: NRPL
    integer :: NSAWFLAG
    integer :: NSYBOL
    integer :: NSYBPA
    integer :: NSYBPB
    integer :: NSYD2F
    integer :: NSYDE2
    integer :: NSYDF3
    integer :: NSYDF4
    integer :: NSYDF6
    integer :: NSYDFD
    integer :: NSYDFH
    integer :: NSYDFT
    integer :: NSYECF
    integer :: NSYGRB
    integer :: NSYIBE
    integer :: NSYIBI
    integer :: NSYJBM
    integer :: NSYJEC
    integer :: NSYJIC
    integer :: NSYKE2
    integer :: NSYKF2
    integer :: NSYKI2
    integer :: NSYKPH
    integer :: NSYLF3
    integer :: NSYLF4
    integer :: NSYLF6
    integer :: NSYLFD
    integer :: NSYLFH
    integer :: NSYLFT
    integer :: NSYLHE
    integer :: NSYLHJ
    integer :: NSYMSE
    integer :: NSYNER
    integer :: NSYNI3
    integer :: NSYNI4
    integer :: NSYNI6
    integer :: NSYNID
    integer :: NSYNIH
    integer :: NSYNIM
    integer :: NSYNIT
    integer :: NSYNMR
    integer :: NSYOMG
    integer :: NSYPRS
    integer :: NSYQBE
    integer :: NSYQBI
    integer :: NSYQEC
    integer :: NSYQIC
    integer :: NSYQPR
    integer :: NSYRES
    integer :: NSYSBI
    integer :: NSYSIM(MIMPS)
    integer :: NSYTER
    integer :: NSYTI2
    integer :: NSYTQI
    integer :: NSYVB2
    integer :: NSYVC3
    integer :: NSYVC4
    integer :: NSYVC6
    integer :: NSYVCD
    integer :: NSYVCH
    integer :: NSYVCT
    integer :: NSYVP2
    integer :: NSYVPO
    integer :: NSYVPR
    integer :: NSYVTR
    integer :: NSYZF2
    integer :: NTIME1
    integer :: NTIME2
    integer :: NTIMEC
    integer :: NTIMLH
    integer :: NTIMNB
    integer :: NTIMRF
    integer :: NTIMRFF
    integer :: NTSAW
    integer :: NXBOL
    integer :: NXBPA
    integer :: NXBPB
    integer :: NXD2F
    integer :: NXDE2
    integer :: NXDF3
    integer :: NXDF4
    integer :: NXDF6
    integer :: NXDFD
    integer :: NXDFH
    integer :: NXDFT
    integer :: NXECF
    integer :: NXGRB
    integer :: NXIBE
    integer :: NXIBI
    integer :: NXJBM
    integer :: NXJEC
    integer :: NXJIC
    integer :: NXKE2
    integer :: NXKF2
    integer :: NXKI2
    integer :: NXKPH
    integer :: NXLF3
    integer :: NXLF4
    integer :: NXLF6
    integer :: NXLFD
    integer :: NXLFH
    integer :: NXLFT
    integer :: NXLHE
    integer :: NXLHJ
    integer :: NXMMX
    integer :: NXMSE
    integer :: NXNE0
    integer :: NXNER
    integer :: NXNI3
    integer :: NXNI4
    integer :: NXNI6
    integer :: NXNID
    integer :: NXNIH
    integer :: NXNIM
    integer :: NXNIT
    integer :: NXNM0
    integer :: NXNMR
    integer :: NXOMG
    integer :: NXPRS
    integer :: NXQBE
    integer :: NXQBI
    integer :: NXQEC
    integer :: NXQIC
    integer :: NXQPR
    integer :: NXRES
    integer :: NXRPL
    integer :: NXSBI
    integer :: NXSIM(MIMPS)
    integer :: NXSYBOL
    integer :: NXSYBPA
    integer :: NXSYBPB
    integer :: NXSYD2F
    integer :: NXSYDE2
    integer :: NXSYDF3
    integer :: NXSYDF4
    integer :: NXSYDF6
    integer :: NXSYDFD
    integer :: NXSYDFH
    integer :: NXSYDFT
    integer :: NXSYECF
    integer :: NXSYGRB
    integer :: NXSYIBE
    integer :: NXSYIBI
    integer :: NXSYJBM
    integer :: NXSYJEC
    integer :: NXSYJIC
    integer :: NXSYKE2
    integer :: NXSYKF2
    integer :: NXSYKI2
    integer :: NXSYKPH
    integer :: NXSYLF3
    integer :: NXSYLF4
    integer :: NXSYLF6
    integer :: NXSYLFD
    integer :: NXSYLFH
    integer :: NXSYLFT
    integer :: NXSYLHE
    integer :: NXSYLHJ
    integer :: NXSYMSE
    integer :: NXSYNER
    integer :: NXSYNI3
    integer :: NXSYNI4
    integer :: NXSYNI6
    integer :: NXSYNID
    integer :: NXSYNIH
    integer :: NXSYNIM
    integer :: NXSYNIT
    integer :: NXSYNMR
    integer :: NXSYOMG
    integer :: NXSYPRS
    integer :: NXSYQBE
    integer :: NXSYQBI
    integer :: NXSYQEC
    integer :: NXSYQIC
    integer :: NXSYQPR
    integer :: NXSYRES
    integer :: NXSYSBI
    integer :: NXSYSIM(MIMPS)
    integer :: NXSYTER
    integer :: NXSYTI2
    integer :: NXSYTQI
    integer :: NXSYVB2
    integer :: NXSYVC3
    integer :: NXSYVC4
    integer :: NXSYVC6
    integer :: NXSYVCD
    integer :: NXSYVCH
    integer :: NXSYVCT
    integer :: NXSYVP2
    integer :: NXSYVPO
    integer :: NXSYVPR
    integer :: NXSYVTR
    integer :: NXSYZF2
    integer :: NXTE0
    integer :: NXTER
    integer :: NXTI2
    integer :: NXTQI
    integer :: NXVB2
    integer :: NXVC3
    integer :: NXVC4
    integer :: NXVC6
    integer :: NXVCD
    integer :: NXVCH
    integer :: NXVCT
    integer :: NXVP2
    integer :: NXVPO
    integer :: NXVPR
    integer :: NXVTR
    integer :: NXZEF2
    integer :: NXZF2
    integer :: NYRPL
    real*8, dimension(:), pointer :: WORKBUF
 
  end type trdatbuf
 
  contains
    integer function tdb_get_MIMPS(idum)
      integer, intent(in) :: idum
 
      tdb_get_MIMPS = MIMPS
 
    end function tdb_get_MIMPS
    integer function tdb_get_MIMPT(idum)
      integer, intent(in) :: idum
 
      tdb_get_MIMPT = MIMPT
 
    end function tdb_get_MIMPT
 
    subroutine trdatbuf_reInit(s)
      type (trdatbuf) :: s
 
      deallocate(s%DATBUF)
      deallocate(s%WORKBUF)
 
      call trdatbuf_init(s)
    end subroutine trdatbuf_reInit
 
    subroutine trdatbuf_init(s)
      type (trdatbuf) :: s
 
      allocate(s%DATBUF(100000)); s%DATBUF = 0
      allocate(s%WORKBUF(100000)); s%WORKBUF = 0
      s%LAIMPS = 0
      s%LAIMPX = 0
      s%LBX = 0
      s%LDATALP = 0
      s%LDATBDI = 0
      s%LDATCUR = 0
      s%LDATDFL = 0
      s%LDATDTG = 0
      s%LDATDTX = 0
      s%LDATEDI = 0
      s%LDATEHP = 0
      s%LDATELI = 0
      s%LDATFIE = 0
      s%LDATFMN = 0
      s%LDATFMX = 0
      s%LDATGAS = 0
      s%LDATGF3 = 0
      s%LDATGF4 = 0
      s%LDATGF6 = 0
      s%LDATGFD = 0
      s%LDATGFH = 0
      s%LDATGFT = 0
      s%LDATGIE = 0
      s%LDATHAL = 0
      s%LDATIBM = 0
      s%LDATIEC = 0
      s%LDATIIC = 0
      s%LDATILH = 0
      s%LDATL2B = 0
      s%LDATLAD = 0
      s%LDATLID = 0
      s%LDATNTX = 0
      s%LDATPBE = 0
      s%LDATPBI = 0
      s%LDATPEB = 0
      s%LDATPEC = 0
      s%LDATPFH = 0
      s%LDATPFL = 0
      s%LDATPIB = 0
      s%LDATPIC = 0
      s%LDATPLF = 0
      s%LDATPLH = 0
      s%LDATPOS = 0
      s%LDATRBZ = 0
      s%LDATRC3 = 0
      s%LDATRC4 = 0
      s%LDATRC6 = 0
      s%LDATRCD = 0
      s%LDATRCH = 0
      s%LDATRCT = 0
      s%LDATRCY = 0
      s%LDATRMN = 0
      s%LDATRTP = 0
      s%LDATSBT = 0
      s%LDATSF3 = 0
      s%LDATSFA = 0
      s%LDATSFL = 0
      s%LDATSFP = 0
      s%LDATSFT = 0
      s%LDATTET = 0
      s%LDATTIT = 0
      s%LDATTPI = 0
      s%LDATTQT = 0
      s%LDATTRF = 0
      s%LDATTXI = 0
      s%LDATVPH = 0
      s%LDATVSB = 0
      s%LDATVSF = 0
      s%LDATXKF = 0
      s%LDATZEF = 0
      s%LDATZFA = 0
      s%LDATZIM = 0
      s%LDATZPL = 0
      s%LDMDF = 0
      s%LDMFR = 0
      s%LDMMX = 0
      s%LDMSE = 0
      s%LFBOL = 0
      s%LFBPA = 0
      s%LFBPB = 0
      s%LFD2F = 0
      s%LFDE2 = 0
      s%LFDF3 = 0
      s%LFDF4 = 0
      s%LFDF6 = 0
      s%LFDFD = 0
      s%LFDFH = 0
      s%LFDFT = 0
      s%LFECF = 0
      s%LFGRB = 0
      s%LFIBE = 0
      s%LFIBI = 0
      s%LFJBM = 0
      s%LFJEC = 0
      s%LFJIC = 0
      s%LFKE2 = 0
      s%LFKF2 = 0
      s%LFKI2 = 0
      s%LFKPH = 0
      s%LFLF3 = 0
      s%LFLF4 = 0
      s%LFLF6 = 0
      s%LFLFD = 0
      s%LFLFH = 0
      s%LFLFT = 0
      s%LFLHE = 0
      s%LFLHJ = 0
      s%LFMSE = 0
      s%LFNER = 0
      s%LFNI3 = 0
      s%LFNI4 = 0
      s%LFNI6 = 0
      s%LFNID = 0
      s%LFNIH = 0
      s%LFNIM = 0
      s%LFNIT = 0
      s%LFNMR = 0
      s%LFOMG = 0
      s%LFPRS = 0
      s%LFQBE = 0
      s%LFQBI = 0
      s%LFQEC = 0
      s%LFQIC = 0
      s%LFQPR = 0
      s%LFREE = 1
      s%LFREE_W = 1
      s%LFRES = 0
      s%LFRQRFF = 0
      s%LFSBI = 0
      s%LFSIM = 0
      s%LFSYBOL = 0
      s%LFSYBPA = 0
      s%LFSYBPB = 0
      s%LFSYD2F = 0
      s%LFSYDE2 = 0
      s%LFSYDF3 = 0
      s%LFSYDF4 = 0
      s%LFSYDF6 = 0
      s%LFSYDFD = 0
      s%LFSYDFH = 0
      s%LFSYDFT = 0
      s%LFSYECF = 0
      s%LFSYGRB = 0
      s%LFSYIBE = 0
      s%LFSYIBI = 0
      s%LFSYJBM = 0
      s%LFSYJEC = 0
      s%LFSYJIC = 0
      s%LFSYKE2 = 0
      s%LFSYKF2 = 0
      s%LFSYKI2 = 0
      s%LFSYKPH = 0
      s%LFSYLF3 = 0
      s%LFSYLF4 = 0
      s%LFSYLF6 = 0
      s%LFSYLFD = 0
      s%LFSYLFH = 0
      s%LFSYLFT = 0
      s%LFSYLHE = 0
      s%LFSYLHJ = 0
      s%LFSYMSE = 0
      s%LFSYNER = 0
      s%LFSYNI3 = 0
      s%LFSYNI4 = 0
      s%LFSYNI6 = 0
      s%LFSYNID = 0
      s%LFSYNIH = 0
      s%LFSYNIM = 0
      s%LFSYNIT = 0
      s%LFSYNMR = 0
      s%LFSYOMG = 0
      s%LFSYPRS = 0
      s%LFSYQBE = 0
      s%LFSYQBI = 0
      s%LFSYQEC = 0
      s%LFSYQIC = 0
      s%LFSYQPR = 0
      s%LFSYRES = 0
      s%LFSYSBI = 0
      s%LFSYSIM = 0
      s%LFSYTER = 0
      s%LFSYTI2 = 0
      s%LFSYTQI = 0
      s%LFSYVB2 = 0
      s%LFSYVC3 = 0
      s%LFSYVC4 = 0
      s%LFSYVC6 = 0
      s%LFSYVCD = 0
      s%LFSYVCH = 0
      s%LFSYVCT = 0
      s%LFSYVP2 = 0
      s%LFSYVPO = 0
      s%LFSYVPR = 0
      s%LFSYVTR = 0
      s%LFSYZF2 = 0
      s%LFTER = 0
      s%LFTI2 = 0
      s%LFTQI = 0
      s%LFULNB = 0
      s%LFVB2 = 0
      s%LFVC3 = 0
      s%LFVC4 = 0
      s%LFVC6 = 0
      s%LFVCD = 0
      s%LFVCH = 0
      s%LFVCT = 0
      s%LFVP2 = 0
      s%LFVPO = 0
      s%LFVPR = 0
      s%LFVTR = 0
      s%LFZF2 = 0
      s%LHLFNB = 0
      s%LMOMD = 0
      s%LPHSLH = 0
      s%LPMDF = 0
      s%LPMSE = 0
      s%LPWREC = 0
      s%LPWRLH = 0
      s%LPWRNB = 0
      s%LPWRRF = 0
      s%LRMFR = 0
      s%LRMP_BDY1 = 0
      s%LRMP_BDY2 = 0
      s%LRMSE = 0
      s%LRPL = 0
      s%LSSYBOL = 0
      s%LSSYBPA = 0
      s%LSSYBPB = 0
      s%LSSYD2F = 0
      s%LSSYDE2 = 0
      s%LSSYDF3 = 0
      s%LSSYDF4 = 0
      s%LSSYDF6 = 0
      s%LSSYDFD = 0
      s%LSSYDFH = 0
      s%LSSYDFT = 0
      s%LSSYECF = 0
      s%LSSYGRB = 0
      s%LSSYIBE = 0
      s%LSSYIBI = 0
      s%LSSYJBM = 0
      s%LSSYJEC = 0
      s%LSSYJIC = 0
      s%LSSYKE2 = 0
      s%LSSYKF2 = 0
      s%LSSYKI2 = 0
      s%LSSYKPH = 0
      s%LSSYLF3 = 0
      s%LSSYLF4 = 0
      s%LSSYLF6 = 0
      s%LSSYLFD = 0
      s%LSSYLFH = 0
      s%LSSYLFT = 0
      s%LSSYLHE = 0
      s%LSSYLHJ = 0
      s%LSSYMSE = 0
      s%LSSYNER = 0
      s%LSSYNI3 = 0
      s%LSSYNI4 = 0
      s%LSSYNI6 = 0
      s%LSSYNID = 0
      s%LSSYNIH = 0
      s%LSSYNIM = 0
      s%LSSYNIT = 0
      s%LSSYNMR = 0
      s%LSSYOMG = 0
      s%LSSYPRS = 0
      s%LSSYQBE = 0
      s%LSSYQBI = 0
      s%LSSYQEC = 0
      s%LSSYQIC = 0
      s%LSSYQPR = 0
      s%LSSYRES = 0
      s%LSSYSBI = 0
      s%LSSYSIM = 0
      s%LSSYTER = 0
      s%LSSYTI2 = 0
      s%LSSYTQI = 0
      s%LSSYVB2 = 0
      s%LSSYVC3 = 0
      s%LSSYVC4 = 0
      s%LSSYVC6 = 0
      s%LSSYVCD = 0
      s%LSSYVCH = 0
      s%LSSYVCT = 0
      s%LSSYVP2 = 0
      s%LSSYVPO = 0
      s%LSSYVPR = 0
      s%LSSYVTR = 0
      s%LSSYZF2 = 0
      s%LTIME1 = 0
      s%LTIME2 = 0
      s%LTIMEC = 0
      s%LTIMLH = 0
      s%LTIMNB = 0
      s%LTIMRF = 0
      s%LTIMRFF = 0
      s%LTSAW = 0
      s%LVLTNB = 0
      s%LXBOL = 0
      s%LXBPA = 0
      s%LXBPB = 0
      s%LXD2F = 0
      s%LXDE2 = 0
      s%LXDF3 = 0
      s%LXDF4 = 0
      s%LXDF6 = 0
      s%LXDFD = 0
      s%LXDFH = 0
      s%LXDFT = 0
      s%LXECF = 0
      s%LXGRB = 0
      s%LXIBE = 0
      s%LXIBI = 0
      s%LXJBM = 0
      s%LXJEC = 0
      s%LXJIC = 0
      s%LXKE2 = 0
      s%LXKF2 = 0
      s%LXKI2 = 0
      s%LXKPH = 0
      s%LXLF3 = 0
      s%LXLF4 = 0
      s%LXLF6 = 0
      s%LXLFD = 0
      s%LXLFH = 0
      s%LXLFT = 0
      s%LXLHE = 0
      s%LXLHJ = 0
      s%LXMMX = 0
      s%LXMSE = 0
      s%LXNER = 0
      s%LXNI3 = 0
      s%LXNI4 = 0
      s%LXNI6 = 0
      s%LXNID = 0
      s%LXNIH = 0
      s%LXNIM = 0
      s%LXNIT = 0
      s%LXNMR = 0
      s%LXOMG = 0
      s%LXPRS = 0
      s%LXQBE = 0
      s%LXQBI = 0
      s%LXQEC = 0
      s%LXQIC = 0
      s%LXQPR = 0
      s%LXRES = 0
      s%LXRPL = 0
      s%LXSBI = 0
      s%LXSIM = 0
      s%LXSYBOL = 0
      s%LXSYBPA = 0
      s%LXSYBPB = 0
      s%LXSYD2F = 0
      s%LXSYDE2 = 0
      s%LXSYDF3 = 0
      s%LXSYDF4 = 0
      s%LXSYDF6 = 0
      s%LXSYDFD = 0
      s%LXSYDFH = 0
      s%LXSYDFT = 0
      s%LXSYECF = 0
      s%LXSYGRB = 0
      s%LXSYIBE = 0
      s%LXSYIBI = 0
      s%LXSYJBM = 0
      s%LXSYJEC = 0
      s%LXSYJIC = 0
      s%LXSYKE2 = 0
      s%LXSYKF2 = 0
      s%LXSYKI2 = 0
      s%LXSYKPH = 0
      s%LXSYLF3 = 0
      s%LXSYLF4 = 0
      s%LXSYLF6 = 0
      s%LXSYLFD = 0
      s%LXSYLFH = 0
      s%LXSYLFT = 0
      s%LXSYLHE = 0
      s%LXSYLHJ = 0
      s%LXSYMSE = 0
      s%LXSYNER = 0
      s%LXSYNI3 = 0
      s%LXSYNI4 = 0
      s%LXSYNI6 = 0
      s%LXSYNID = 0
      s%LXSYNIH = 0
      s%LXSYNIM = 0
      s%LXSYNIT = 0
      s%LXSYNMR = 0
      s%LXSYOMG = 0
      s%LXSYPRS = 0
      s%LXSYQBE = 0
      s%LXSYQBI = 0
      s%LXSYQEC = 0
      s%LXSYQIC = 0
      s%LXSYQPR = 0
      s%LXSYRES = 0
      s%LXSYSBI = 0
      s%LXSYSIM = 0
      s%LXSYTER = 0
      s%LXSYTI2 = 0
      s%LXSYTQI = 0
      s%LXSYVB2 = 0
      s%LXSYVC3 = 0
      s%LXSYVC4 = 0
      s%LXSYVC6 = 0
      s%LXSYVCD = 0
      s%LXSYVCH = 0
      s%LXSYVCT = 0
      s%LXSYVP2 = 0
      s%LXSYVPO = 0
      s%LXSYVPR = 0
      s%LXSYVTR = 0
      s%LXSYZF2 = 0
      s%LXTER = 0
      s%LXTI2 = 0
      s%LXTQI = 0
      s%LXVB2 = 0
      s%LXVC3 = 0
      s%LXVC4 = 0
      s%LXVC6 = 0
      s%LXVCD = 0
      s%LXVCH = 0
      s%LXVCT = 0
      s%LXVP2 = 0
      s%LXVPO = 0
      s%LXVPR = 0
      s%LXVTR = 0
      s%LXZF2 = 0
      s%LXZIMPS = 0
      s%LXZIMPX = 0
      s%LXZIMPXS = 0
      s%LYRPL = 0
      s%LYSIM = 0
      s%MMAX = 0
      s%NANTECH_D = 0
      s%NANTICH_D = 0
      s%NANTLH_D = 0
      s%NBDATA = 0
      s%NBX = 0
      s%NDMDF = 0
      s%NDMFR = 0
      s%NDMMX = 0
      s%NDMSE = 0
      s%NFRBCODE = 0
      s%NFRBMODE = 0
      s%NHECFT = 0
      s%NHFMX = 0
      s%NIMDF = 0
      s%NISSIM = 0
      s%NISX = 0
      s%NITSIM = 0
      s%NITX = 0
      s%NMAPSIM = 0
      s%NMDXKF = 0
      s%NMIMP = 0
      s%NMOMD = 0
      s%NNSIM = 0
      s%NPMDF = 0
      s%NPMSE = 0
      s%NRHIS = 0
      s%NRHIX = 0
      s%NRIBOL = -9999
      s%NRIBPA = -9999
      s%NRIBPB = -9999
      s%NRID2F = -9999
      s%NRIDE2 = -9999
      s%NRIDF3 = -9999
      s%NRIDF4 = -9999
      s%NRIDF6 = -9999
      s%NRIDFD = -9999
      s%NRIDFH = -9999
      s%NRIDFT = -9999
      s%NRIECF = -9999
      s%NRIGRB = -9999
      s%NRIIBE = -9999
      s%NRIIBI = -9999
      s%NRIJBM = -9999
      s%NRIJEC = -9999
      s%NRIJIC = -9999
      s%NRIKE2 = -9999
      s%NRIKF2 = -9999
      s%NRIKI2 = -9999
      s%NRIKPH = -9999
      s%NRILF3 = -9999
      s%NRILF4 = -9999
      s%NRILF6 = -9999
      s%NRILFD = -9999
      s%NRILFH = -9999
      s%NRILFT = -9999
      s%NRILHE = -9999
      s%NRILHJ = -9999
      s%NRIMSE = -9999
      s%NRINER = -9999
      s%NRINI3 = -9999
      s%NRINI4 = -9999
      s%NRINI6 = -9999
      s%NRINID = -9999
      s%NRINIH = -9999
      s%NRINIM = -9999
      s%NRINIT = -9999
      s%NRINMR = -9999
      s%NRIOMG = -9999
      s%NRIPRS = -9999
      s%NRIQBE = -9999
      s%NRIQBI = -9999
      s%NRIQEC = -9999
      s%NRIQIC = -9999
      s%NRIQPR = -9999
      s%NRIRES = -9999
      s%NRISBI = -9999
      s%NRISIM = -9999
      s%NRITER = -9999
      s%NRITI2 = -9999
      s%NRITQI = -9999
      s%NRIVB2 = -9999
      s%NRIVC3 = -9999
      s%NRIVC4 = -9999
      s%NRIVC6 = -9999
      s%NRIVCD = -9999
      s%NRIVCH = -9999
      s%NRIVCT = -9999
      s%NRIVP2 = -9999
      s%NRIVPO = -9999
      s%NRIVPR = -9999
      s%NRIVTR = -9999
      s%NRIZF2 = -9999
      s%NRMFR = 0
      s%NRMSE = 0
      s%NRPL = 0
      s%NSAWFLAG = 0
      s%NSYBOL = -9999
      s%NSYBPA = -9999
      s%NSYBPB = -9999
      s%NSYD2F = -9999
      s%NSYDE2 = -9999
      s%NSYDF3 = -9999
      s%NSYDF4 = -9999
      s%NSYDF6 = -9999
      s%NSYDFD = -9999
      s%NSYDFH = -9999
      s%NSYDFT = -9999
      s%NSYECF = -9999
      s%NSYGRB = -9999
      s%NSYIBE = -9999
      s%NSYIBI = -9999
      s%NSYJBM = -9999
      s%NSYJEC = -9999
      s%NSYJIC = -9999
      s%NSYKE2 = -9999
      s%NSYKF2 = -9999
      s%NSYKI2 = -9999
      s%NSYKPH = -9999
      s%NSYLF3 = -9999
      s%NSYLF4 = -9999
      s%NSYLF6 = -9999
      s%NSYLFD = -9999
      s%NSYLFH = -9999
      s%NSYLFT = -9999
      s%NSYLHE = -9999
      s%NSYLHJ = -9999
      s%NSYMSE = -9999
      s%NSYNER = -9999
      s%NSYNI3 = -9999
      s%NSYNI4 = -9999
      s%NSYNI6 = -9999
      s%NSYNID = -9999
      s%NSYNIH = -9999
      s%NSYNIM = -9999
      s%NSYNIT = -9999
      s%NSYNMR = -9999
      s%NSYOMG = -9999
      s%NSYPRS = -9999
      s%NSYQBE = -9999
      s%NSYQBI = -9999
      s%NSYQEC = -9999
      s%NSYQIC = -9999
      s%NSYQPR = -9999
      s%NSYRES = -9999
      s%NSYSBI = -9999
      s%NSYSIM = -9999
      s%NSYTER = -9999
      s%NSYTI2 = -9999
      s%NSYTQI = -9999
      s%NSYVB2 = -9999
      s%NSYVC3 = -9999
      s%NSYVC4 = -9999
      s%NSYVC6 = -9999
      s%NSYVCD = -9999
      s%NSYVCH = -9999
      s%NSYVCT = -9999
      s%NSYVP2 = -9999
      s%NSYVPO = -9999
      s%NSYVPR = -9999
      s%NSYVTR = -9999
      s%NSYZF2 = -9999
      s%NTIME1 = 0
      s%NTIME2 = 0
      s%NTIMEC = 0
      s%NTIMLH = 0
      s%NTIMNB = 0
      s%NTIMRF = 0
      s%NTIMRFF = 0
      s%NTSAW = 0
      s%NXBOL = -9999
      s%NXBPA = -9999
      s%NXBPB = -9999
      s%NXD2F = -9999
      s%NXDE2 = -9999
      s%NXDF3 = -9999
      s%NXDF4 = -9999
      s%NXDF6 = -9999
      s%NXDFD = -9999
      s%NXDFH = -9999
      s%NXDFT = -9999
      s%NXECF = -9999
      s%NXGRB = -9999
      s%NXIBE = -9999
      s%NXIBI = -9999
      s%NXJBM = -9999
      s%NXJEC = -9999
      s%NXJIC = -9999
      s%NXKE2 = -9999
      s%NXKF2 = -9999
      s%NXKI2 = -9999
      s%NXKPH = -9999
      s%NXLF3 = -9999
      s%NXLF4 = -9999
      s%NXLF6 = -9999
      s%NXLFD = -9999
      s%NXLFH = -9999
      s%NXLFT = -9999
      s%NXLHE = -9999
      s%NXLHJ = -9999
      s%NXMMX = 0
      s%NXMSE = -9999
      s%NXNE0 = -9999
      s%NXNER = -9999
      s%NXNI3 = -9999
      s%NXNI4 = -9999
      s%NXNI6 = -9999
      s%NXNID = -9999
      s%NXNIH = -9999
      s%NXNIM = -9999
      s%NXNIT = -9999
      s%NXNM0 = -9999
      s%NXNMR = -9999
      s%NXOMG = -9999
      s%NXPRS = -9999
      s%NXQBE = -9999
      s%NXQBI = -9999
      s%NXQEC = -9999
      s%NXQIC = -9999
      s%NXQPR = -9999
      s%NXRES = -9999
      s%NXRPL = 0
      s%NXSBI = -9999
      s%NXSIM = -9999
      s%NXSYBOL = 0
      s%NXSYBPA = 0
      s%NXSYBPB = 0
      s%NXSYD2F = 0
      s%NXSYDE2 = 0
      s%NXSYDF3 = 0
      s%NXSYDF4 = 0
      s%NXSYDF6 = 0
      s%NXSYDFD = 0
      s%NXSYDFH = 0
      s%NXSYDFT = 0
      s%NXSYECF = 0
      s%NXSYGRB = 0
      s%NXSYIBE = 0
      s%NXSYIBI = 0
      s%NXSYJBM = 0
      s%NXSYJEC = 0
      s%NXSYJIC = 0
      s%NXSYKE2 = 0
      s%NXSYKF2 = 0
      s%NXSYKI2 = 0
      s%NXSYKPH = 0
      s%NXSYLF3 = 0
      s%NXSYLF4 = 0
      s%NXSYLF6 = 0
      s%NXSYLFD = 0
      s%NXSYLFH = 0
      s%NXSYLFT = 0
      s%NXSYLHE = 0
      s%NXSYLHJ = 0
      s%NXSYMSE = 0
      s%NXSYNER = 0
      s%NXSYNI3 = 0
      s%NXSYNI4 = 0
      s%NXSYNI6 = 0
      s%NXSYNID = 0
      s%NXSYNIH = 0
      s%NXSYNIM = 0
      s%NXSYNIT = 0
      s%NXSYNMR = 0
      s%NXSYOMG = 0
      s%NXSYPRS = 0
      s%NXSYQBE = 0
      s%NXSYQBI = 0
      s%NXSYQEC = 0
      s%NXSYQIC = 0
      s%NXSYQPR = 0
      s%NXSYRES = 0
      s%NXSYSBI = 0
      s%NXSYSIM = 0
      s%NXSYTER = 0
      s%NXSYTI2 = 0
      s%NXSYTQI = 0
      s%NXSYVB2 = 0
      s%NXSYVC3 = 0
      s%NXSYVC4 = 0
      s%NXSYVC6 = 0
      s%NXSYVCD = 0
      s%NXSYVCH = 0
      s%NXSYVCT = 0
      s%NXSYVP2 = 0
      s%NXSYVPO = 0
      s%NXSYVPR = 0
      s%NXSYVTR = 0
      s%NXSYZF2 = 0
      s%NXTE0 = -9999
      s%NXTER = -9999
      s%NXTI2 = -9999
      s%NXTQI = -9999
      s%NXVB2 = -9999
      s%NXVC3 = -9999
      s%NXVC4 = -9999
      s%NXVC6 = -9999
      s%NXVCD = -9999
      s%NXVCH = -9999
      s%NXVCT = -9999
      s%NXVP2 = -9999
      s%NXVPO = -9999
      s%NXVPR = -9999
      s%NXVTR = -9999
      s%NXZEF2 = -9999
      s%NXZF2 = -9999
      s%NYRPL = 0
 
    end subroutine trdatbuf_init
    logical function tdb_present1(d,ztrigraph,iaddr)
      type (trdatbuf) :: d
      character*(*), intent(in) :: ztrigraph
      integer, intent(out) :: iaddr
 
      character*3 ztri
      integer :: lunmsg_tdb
 
      iaddr = -1
      ztri = ztrigraph(1:min(3,len(ztrigraph)))
      call uupper(ztri)  ! convert to upper case (portlib routine)
 
      if(ztri.eq.'ALP') then
         iaddr = d%LDATALP
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'BDI') then
         iaddr = d%LDATBDI
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'CUR') then
         iaddr = d%LDATCUR
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DFL') then
         iaddr = d%LDATDFL
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DTG') then
         iaddr = d%LDATDTG
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DTX') then
         iaddr = d%LDATDTX
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'EDI') then
         iaddr = d%LDATEDI
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'EHP') then
         iaddr = d%LDATEHP
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ELI') then
         iaddr = d%LDATELI
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'FIE') then
         iaddr = d%LDATFIE
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'FMN') then
         iaddr = d%LDATFMN
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'FMX') then
         iaddr = d%LDATFMX
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GAS') then
         iaddr = d%LDATGAS
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GF3') then
         iaddr = d%LDATGF3
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GF4') then
         iaddr = d%LDATGF4
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GF6') then
         iaddr = d%LDATGF6
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GFD') then
         iaddr = d%LDATGFD
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GFH') then
         iaddr = d%LDATGFH
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GFT') then
         iaddr = d%LDATGFT
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GIE') then
         iaddr = d%LDATGIE
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'HAL') then
         iaddr = d%LDATHAL
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'IBM') then
         iaddr = d%LDATIBM
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'IEC') then
         iaddr = d%LDATIEC
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'IIC') then
         iaddr = d%LDATIIC
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ILH') then
         iaddr = d%LDATILH
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'L2B') then
         iaddr = d%LDATL2B
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LAD') then
         iaddr = d%LDATLAD
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LID') then
         iaddr = d%LDATLID
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NTX') then
         iaddr = d%LDATNTX
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PBE') then
         iaddr = d%LDATPBE
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PBI') then
         iaddr = d%LDATPBI
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PEB') then
         iaddr = d%LDATPEB
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PEC') then
         iaddr = d%LDATPEC
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PFH') then
         iaddr = d%LDATPFH
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PFL') then
         iaddr = d%LDATPFL
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PIB') then
         iaddr = d%LDATPIB
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PIC') then
         iaddr = d%LDATPIC
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PLF') then
         iaddr = d%LDATPLF
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PLH') then
         iaddr = d%LDATPLH
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'POS') then
         iaddr = d%LDATPOS
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RBZ') then
         iaddr = d%LDATRBZ
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RC3') then
         iaddr = d%LDATRC3
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RC4') then
         iaddr = d%LDATRC4
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RC6') then
         iaddr = d%LDATRC6
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RCD') then
         iaddr = d%LDATRCD
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RCH') then
         iaddr = d%LDATRCH
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RCT') then
         iaddr = d%LDATRCT
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RCY') then
         iaddr = d%LDATRCY
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RMN') then
         iaddr = d%LDATRMN
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RTP') then
         iaddr = d%LDATRTP
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SBT') then
         iaddr = d%LDATSBT
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SF3') then
         iaddr = d%LDATSF3
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SFA') then
         iaddr = d%LDATSFA
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SFL') then
         iaddr = d%LDATSFL
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SFP') then
         iaddr = d%LDATSFP
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SFT') then
         iaddr = d%LDATSFT
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TET') then
         iaddr = d%LDATTET
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TIT') then
         iaddr = d%LDATTIT
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TPI') then
         iaddr = d%LDATTPI
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TQT') then
         iaddr = d%LDATTQT
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TRF') then
         iaddr = d%LDATTRF
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TXI') then
         iaddr = d%LDATTXI
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VPH') then
         iaddr = d%LDATVPH
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VSB') then
         iaddr = d%LDATVSB
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VSF') then
         iaddr = d%LDATVSF
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'XKF') then
         iaddr = d%LDATXKF
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ZEF') then
         iaddr = d%LDATZEF
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ZFA') then
         iaddr = d%LDATZFA
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ZIM') then
         iaddr = d%LDATZIM
         tdb_present1 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ZPL') then
         iaddr = d%LDATZPL
         tdb_present1 = (iaddr.gt.0)
      endif
 
      if(iaddr.eq.-1) then
         write(lunmsg_tdb(0),*) ' ?tdb_present1: unknown scalar data type: ', &
               ztri
         tdb_present1 = .FALSE.
      endif
    end function tdb_present1
    logical function tdb_present2(d,ztrigraph,iaddr)
      type (trdatbuf) :: d
      character*(*), intent(in) :: ztrigraph
      integer, intent(out) :: iaddr
 
      character*3 ztri
      integer :: lunmsg_tdb
 
      iaddr = -1
      ztri = ztrigraph(1:min(3,len(ztrigraph)))
      call uupper(ztri)  ! convert to upper case (portlib routine)
 
      if(ztri.eq.'BOL') then
         iaddr = d%LFBOL
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'BPA') then
         iaddr = d%LFBPA
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'BPB') then
         iaddr = d%LFBPB
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'D2F') then
         iaddr = d%LFD2F
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DE2') then
         iaddr = d%LFDE2
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DF3') then
         iaddr = d%LFDF3
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DF4') then
         iaddr = d%LFDF4
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DF6') then
         iaddr = d%LFDF6
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DFD') then
         iaddr = d%LFDFD
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DFH') then
         iaddr = d%LFDFH
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'DFT') then
         iaddr = d%LFDFT
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ECF') then
         iaddr = d%LFECF
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'GRB') then
         iaddr = d%LFGRB
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'IBE') then
         iaddr = d%LFIBE
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'IBI') then
         iaddr = d%LFIBI
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'JBM') then
         iaddr = d%LFJBM
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'JEC') then
         iaddr = d%LFJEC
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'JIC') then
         iaddr = d%LFJIC
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'KE2') then
         iaddr = d%LFKE2
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'KF2') then
         iaddr = d%LFKF2
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'KI2') then
         iaddr = d%LFKI2
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'KPH') then
         iaddr = d%LFKPH
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LF3') then
         iaddr = d%LFLF3
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LF4') then
         iaddr = d%LFLF4
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LF6') then
         iaddr = d%LFLF6
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LFD') then
         iaddr = d%LFLFD
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LFH') then
         iaddr = d%LFLFH
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LFT') then
         iaddr = d%LFLFT
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LHE') then
         iaddr = d%LFLHE
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'LHJ') then
         iaddr = d%LFLHJ
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'MSE') then
         iaddr = d%LFMSE
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NER') then
         iaddr = d%LFNER
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NI3') then
         iaddr = d%LFNI3
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NI4') then
         iaddr = d%LFNI4
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NI6') then
         iaddr = d%LFNI6
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NID') then
         iaddr = d%LFNID
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NIH') then
         iaddr = d%LFNIH
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NIM') then
         iaddr = d%LFNIM
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NIT') then
         iaddr = d%LFNIT
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'NMR') then
         iaddr = d%LFNMR
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'OMG') then
         iaddr = d%LFOMG
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'PRS') then
         iaddr = d%LFPRS
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'QBE') then
         iaddr = d%LFQBE
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'QBI') then
         iaddr = d%LFQBI
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'QEC') then
         iaddr = d%LFQEC
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'QIC') then
         iaddr = d%LFQIC
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'QPR') then
         iaddr = d%LFQPR
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'RES') then
         iaddr = d%LFRES
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SBI') then
         iaddr = d%LFSBI
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'SIM') then
         iaddr = maxval(d%LFSIM)
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TER') then
         iaddr = d%LFTER
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TI2') then
         iaddr = d%LFTI2
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'TQI') then
         iaddr = d%LFTQI
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VB2') then
         iaddr = d%LFVB2
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VC3') then
         iaddr = d%LFVC3
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VC4') then
         iaddr = d%LFVC4
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VC6') then
         iaddr = d%LFVC6
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VCD') then
         iaddr = d%LFVCD
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VCH') then
         iaddr = d%LFVCH
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VCT') then
         iaddr = d%LFVCT
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VP2') then
         iaddr = d%LFVP2
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VPO') then
         iaddr = d%LFVPO
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VPR') then
         iaddr = d%LFVPR
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'VTR') then
         iaddr = d%LFVTR
         tdb_present2 = (iaddr.gt.0)
      endif
      if(ztri.eq.'ZF2') then
         iaddr = d%LFZF2
         tdb_present2 = (iaddr.gt.0)
      endif
 
      if(iaddr.eq.-1) then
         write(lunmsg_tdb(0),*) ' ?tdb_present2: unknown profile data type: ', &
               ztri
         tdb_present2 = .FALSE.
      endif
    end function tdb_present2
    subroutine trdatbuf_expand(arr,ineed,isize_new)
 
      ! check size of 1d pointer array; expand & copy if necessary
 
      real*8, dimension(:), pointer :: arr
      integer, intent(in) :: ineed      ! min. size datbuf needed
      integer, intent(out) :: isize_new ! actual datbuf size
 
      integer :: isize_old,istat
      real*8, dimension(:), pointer :: ztmp
      real*8, parameter :: ZERO = 0.0d0
 
      !-----------------------------------------
 
      isize_new = size(arr)
      if(ineed.le.isize_new) return
 
      !  bigger buffer needed
 
      isize_old = isize_new
 
      do
        isize_new = 2*isize_new
        if(isize_new.gt.ineed) exit
      enddo
 
      allocate(ztmp(isize_new),stat=istat)
      if(istat.ne.0) then
        call errmsg_exit(' ?? trdatbuf_expand: memory alloc failed.')
      endif
 
      ztmp(1:isize_old) = arr
      ztmp(isize_old+1:isize_new) = ZERO
      deallocate(arr)
 
      arr => ztmp
    end subroutine trdatbuf_expand
 
    subroutine DATBUF_expand(s,ineed,isize_new)
 
      type (trdatbuf) :: s
      integer, intent(in) :: ineed       ! min. size datbuf needed
      integer, intent(out) :: isize_new  ! actual datbuf size
 
      call trdatbuf_expand(s%DATBUF,ineed,isize_new)
    end subroutine DATBUF_expand
    subroutine WORKBUF_expand(s,ineed,isize_new)
 
      type (trdatbuf) :: s
      integer, intent(in) :: ineed       ! min. size datbuf needed
      integer, intent(out) :: isize_new  ! actual datbuf size
 
      call trdatbuf_expand(s%WORKBUF,ineed,isize_new)
    end subroutine WORKBUF_expand
 
end module trdatbuf_obj_tsc
